# GENERATED by tools/macro_floorplan.py — top-level macro floorplan.
# Hard-macro placement of yolo26n_core (conv stages + blocks + skip FIFOs).
set PDK /home/marty/Documents/aif/pdk/asap7
read_lef     $PDK/lef/asap7_tech_1x.lef
read_lef     $PDK/lef/asap7_R_1x.lef
read_lef     pnr/top/blocks.lef
read_verilog pnr/top/top_macro.v
link_design  yolo26n_top

initialize_floorplan -die_area "0 0 1925.41 1925.41" \
                     -core_area "5.0 5.0 1920.41 1920.41" \
                     -site asap7sc7p5t
source $PDK/make_tracks.tcl

# place top-level I/O pins, then hard-macro placement (RTL-MP, mpl).
place_pins -hor_layers M4 -ver_layers M5
set_thread_count 8
rtl_macro_placer -halo_width 2.0 -target_util 0.82
write_def pnr/top/yolo26n_top.def
report_design_area
exit
