// Copyright (c) 2026 vibeyolo
// SPDX-License-Identifier: Apache-2.0
//
// scale_pkg.sv — auto-generated per-layer parallelism + shape parameters.
// Generated by integ/scale/gen_scale_pkg.py with T_FRAME = 100000.
// Layer count: 102
//
// For each layer i, exposes:
//   P_PIX_i, P_COUT_i, P_CIN_i      parallelism factors
//   H_i, W_i, K_i                   output H, W, kernel size (Kh==Kw)
//   CIN_i, COUT_i                   channel counts
//   STRIDE_i, PAD_i                 stride and pad (symmetric)

// verilator lint_off UNUSEDPARAM
package scale_pkg;

  localparam int T_FRAME    = 100000;
  localparam int NUM_LAYERS = 102;

  // L0: /model.0/conv/Conv_quant
  //   shape  Cin=3 Cout=16 K=3 stride=2 pad=1 group=1
  //   H_in=640 W_in=640 H_out=320 W_out=320
  //   M=44236800  cycles=51200  (target T=100000)
  localparam int LAYER_0_P_PIX  = 2;
  localparam int LAYER_0_P_COUT = 16;
  localparam int LAYER_0_P_CIN  = 3;
  localparam int LAYER_0_H      = 320;
  localparam int LAYER_0_W      = 320;
  localparam int LAYER_0_K      = 3;
  localparam int LAYER_0_CIN    = 3;
  localparam int LAYER_0_COUT   = 16;
  localparam int LAYER_0_STRIDE = 2;
  localparam int LAYER_0_PAD    = 1;
  localparam int LAYER_0_GROUP  = 1;
  localparam int LAYER_0_CYCLES = 51200;

  // L1: /model.1/conv/Conv_quant
  //   shape  Cin=16 Cout=32 K=3 stride=2 pad=1 group=1
  //   H_in=320 W_in=320 H_out=160 W_out=160
  //   M=117964800  cycles=51200  (target T=100000)
  localparam int LAYER_1_P_PIX  = 1;
  localparam int LAYER_1_P_COUT = 32;
  localparam int LAYER_1_P_CIN  = 8;
  localparam int LAYER_1_H      = 160;
  localparam int LAYER_1_W      = 160;
  localparam int LAYER_1_K      = 3;
  localparam int LAYER_1_CIN    = 16;
  localparam int LAYER_1_COUT   = 32;
  localparam int LAYER_1_STRIDE = 2;
  localparam int LAYER_1_PAD    = 1;
  localparam int LAYER_1_GROUP  = 1;
  localparam int LAYER_1_CYCLES = 51200;

  // L2: /model.2/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=160 W_in=160 H_out=160 W_out=160
  //   M=26214400  cycles=51200  (target T=100000)
  localparam int LAYER_2_P_PIX  = 1;
  localparam int LAYER_2_P_COUT = 32;
  localparam int LAYER_2_P_CIN  = 16;
  localparam int LAYER_2_H      = 160;
  localparam int LAYER_2_W      = 160;
  localparam int LAYER_2_K      = 1;
  localparam int LAYER_2_CIN    = 32;
  localparam int LAYER_2_COUT   = 32;
  localparam int LAYER_2_STRIDE = 1;
  localparam int LAYER_2_PAD    = 0;
  localparam int LAYER_2_GROUP  = 1;
  localparam int LAYER_2_CYCLES = 51200;

  // L3: /model.2/m.0/cv1/conv/Conv_quant
  //   shape  Cin=16 Cout=8 K=3 stride=1 pad=1 group=1
  //   H_in=160 W_in=160 H_out=160 W_out=160
  //   M=29491200  cycles=51200  (target T=100000)
  localparam int LAYER_3_P_PIX  = 1;
  localparam int LAYER_3_P_COUT = 8;
  localparam int LAYER_3_P_CIN  = 8;
  localparam int LAYER_3_H      = 160;
  localparam int LAYER_3_W      = 160;
  localparam int LAYER_3_K      = 3;
  localparam int LAYER_3_CIN    = 16;
  localparam int LAYER_3_COUT   = 8;
  localparam int LAYER_3_STRIDE = 1;
  localparam int LAYER_3_PAD    = 1;
  localparam int LAYER_3_GROUP  = 1;
  localparam int LAYER_3_CYCLES = 51200;

  // L4: /model.2/m.0/cv2/conv/Conv_quant
  //   shape  Cin=8 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=160 W_in=160 H_out=160 W_out=160
  //   M=29491200  cycles=51200  (target T=100000)
  localparam int LAYER_4_P_PIX  = 1;
  localparam int LAYER_4_P_COUT = 16;
  localparam int LAYER_4_P_CIN  = 4;
  localparam int LAYER_4_H      = 160;
  localparam int LAYER_4_W      = 160;
  localparam int LAYER_4_K      = 3;
  localparam int LAYER_4_CIN    = 8;
  localparam int LAYER_4_COUT   = 16;
  localparam int LAYER_4_STRIDE = 1;
  localparam int LAYER_4_PAD    = 1;
  localparam int LAYER_4_GROUP  = 1;
  localparam int LAYER_4_CYCLES = 51200;

  // L5: /model.2/cv2/conv/Conv_quant
  //   shape  Cin=48 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=160 W_in=160 H_out=160 W_out=160
  //   M=78643200  cycles=76800  (target T=100000)
  localparam int LAYER_5_P_PIX  = 1;
  localparam int LAYER_5_P_COUT = 64;
  localparam int LAYER_5_P_CIN  = 16;
  localparam int LAYER_5_H      = 160;
  localparam int LAYER_5_W      = 160;
  localparam int LAYER_5_K      = 1;
  localparam int LAYER_5_CIN    = 48;
  localparam int LAYER_5_COUT   = 64;
  localparam int LAYER_5_STRIDE = 1;
  localparam int LAYER_5_PAD    = 0;
  localparam int LAYER_5_GROUP  = 1;
  localparam int LAYER_5_CYCLES = 76800;

  // L6: /model.3/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=3 stride=2 pad=1 group=1
  //   H_in=160 W_in=160 H_out=80 W_out=80
  //   M=235929600  cycles=51200  (target T=100000)
  localparam int LAYER_6_P_PIX  = 1;
  localparam int LAYER_6_P_COUT = 64;
  localparam int LAYER_6_P_CIN  = 8;
  localparam int LAYER_6_H      = 80;
  localparam int LAYER_6_W      = 80;
  localparam int LAYER_6_K      = 3;
  localparam int LAYER_6_CIN    = 64;
  localparam int LAYER_6_COUT   = 64;
  localparam int LAYER_6_STRIDE = 2;
  localparam int LAYER_6_PAD    = 1;
  localparam int LAYER_6_GROUP  = 1;
  localparam int LAYER_6_CYCLES = 51200;

  // L7: /model.4/cv1/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=26214400  cycles=51200  (target T=100000)
  localparam int LAYER_7_P_PIX  = 1;
  localparam int LAYER_7_P_COUT = 64;
  localparam int LAYER_7_P_CIN  = 8;
  localparam int LAYER_7_H      = 80;
  localparam int LAYER_7_W      = 80;
  localparam int LAYER_7_K      = 1;
  localparam int LAYER_7_CIN    = 64;
  localparam int LAYER_7_COUT   = 64;
  localparam int LAYER_7_STRIDE = 1;
  localparam int LAYER_7_PAD    = 0;
  localparam int LAYER_7_GROUP  = 1;
  localparam int LAYER_7_CYCLES = 51200;

  // L8: /model.4/m.0/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=29491200  cycles=51200  (target T=100000)
  localparam int LAYER_8_P_PIX  = 1;
  localparam int LAYER_8_P_COUT = 16;
  localparam int LAYER_8_P_CIN  = 4;
  localparam int LAYER_8_H      = 80;
  localparam int LAYER_8_W      = 80;
  localparam int LAYER_8_K      = 3;
  localparam int LAYER_8_CIN    = 32;
  localparam int LAYER_8_COUT   = 16;
  localparam int LAYER_8_STRIDE = 1;
  localparam int LAYER_8_PAD    = 1;
  localparam int LAYER_8_GROUP  = 1;
  localparam int LAYER_8_CYCLES = 51200;

  // L9: /model.4/m.0/cv2/conv/Conv_quant
  //   shape  Cin=16 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=29491200  cycles=51200  (target T=100000)
  localparam int LAYER_9_P_PIX  = 1;
  localparam int LAYER_9_P_COUT = 32;
  localparam int LAYER_9_P_CIN  = 2;
  localparam int LAYER_9_H      = 80;
  localparam int LAYER_9_W      = 80;
  localparam int LAYER_9_K      = 3;
  localparam int LAYER_9_CIN    = 16;
  localparam int LAYER_9_COUT   = 32;
  localparam int LAYER_9_STRIDE = 1;
  localparam int LAYER_9_PAD    = 1;
  localparam int LAYER_9_GROUP  = 1;
  localparam int LAYER_9_CYCLES = 51200;

  // L10: /model.4/cv2/conv/Conv_quant
  //   shape  Cin=96 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=78643200  cycles=76800  (target T=100000)
  localparam int LAYER_10_P_PIX  = 1;
  localparam int LAYER_10_P_COUT = 128;
  localparam int LAYER_10_P_CIN  = 8;
  localparam int LAYER_10_H      = 80;
  localparam int LAYER_10_W      = 80;
  localparam int LAYER_10_K      = 1;
  localparam int LAYER_10_CIN    = 96;
  localparam int LAYER_10_COUT   = 128;
  localparam int LAYER_10_STRIDE = 1;
  localparam int LAYER_10_PAD    = 0;
  localparam int LAYER_10_GROUP  = 1;
  localparam int LAYER_10_CYCLES = 76800;

  // L11: /model.5/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=3 stride=2 pad=1 group=1
  //   H_in=80 W_in=80 H_out=40 W_out=40
  //   M=235929600  cycles=51200  (target T=100000)
  localparam int LAYER_11_P_PIX  = 1;
  localparam int LAYER_11_P_COUT = 128;
  localparam int LAYER_11_P_CIN  = 4;
  localparam int LAYER_11_H      = 40;
  localparam int LAYER_11_W      = 40;
  localparam int LAYER_11_K      = 3;
  localparam int LAYER_11_CIN    = 128;
  localparam int LAYER_11_COUT   = 128;
  localparam int LAYER_11_STRIDE = 2;
  localparam int LAYER_11_PAD    = 1;
  localparam int LAYER_11_GROUP  = 1;
  localparam int LAYER_11_CYCLES = 51200;

  // L12: /model.6/cv1/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=26214400  cycles=51200  (target T=100000)
  localparam int LAYER_12_P_PIX  = 1;
  localparam int LAYER_12_P_COUT = 128;
  localparam int LAYER_12_P_CIN  = 4;
  localparam int LAYER_12_H      = 40;
  localparam int LAYER_12_W      = 40;
  localparam int LAYER_12_K      = 1;
  localparam int LAYER_12_CIN    = 128;
  localparam int LAYER_12_COUT   = 128;
  localparam int LAYER_12_STRIDE = 1;
  localparam int LAYER_12_PAD    = 0;
  localparam int LAYER_12_GROUP  = 1;
  localparam int LAYER_12_CYCLES = 51200;

  // L13: /model.6/m.0/cv1/conv/Conv_quant
  //   shape  Cin=64 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_13_P_PIX  = 1;
  localparam int LAYER_13_P_COUT = 32;
  localparam int LAYER_13_P_CIN  = 2;
  localparam int LAYER_13_H      = 40;
  localparam int LAYER_13_W      = 40;
  localparam int LAYER_13_K      = 1;
  localparam int LAYER_13_CIN    = 64;
  localparam int LAYER_13_COUT   = 32;
  localparam int LAYER_13_STRIDE = 1;
  localparam int LAYER_13_PAD    = 0;
  localparam int LAYER_13_GROUP  = 1;
  localparam int LAYER_13_CYCLES = 51200;

  // L14: /model.6/m.0/cv2/conv/Conv_quant
  //   shape  Cin=64 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_14_P_PIX  = 1;
  localparam int LAYER_14_P_COUT = 32;
  localparam int LAYER_14_P_CIN  = 2;
  localparam int LAYER_14_H      = 40;
  localparam int LAYER_14_W      = 40;
  localparam int LAYER_14_K      = 1;
  localparam int LAYER_14_CIN    = 64;
  localparam int LAYER_14_COUT   = 32;
  localparam int LAYER_14_STRIDE = 1;
  localparam int LAYER_14_PAD    = 0;
  localparam int LAYER_14_GROUP  = 1;
  localparam int LAYER_14_CYCLES = 51200;

  // L15: /model.6/m.0/m/m.0/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_15_P_PIX  = 1;
  localparam int LAYER_15_P_COUT = 32;
  localparam int LAYER_15_P_CIN  = 1;
  localparam int LAYER_15_H      = 40;
  localparam int LAYER_15_W      = 40;
  localparam int LAYER_15_K      = 3;
  localparam int LAYER_15_CIN    = 32;
  localparam int LAYER_15_COUT   = 32;
  localparam int LAYER_15_STRIDE = 1;
  localparam int LAYER_15_PAD    = 1;
  localparam int LAYER_15_GROUP  = 1;
  localparam int LAYER_15_CYCLES = 51200;

  // L16: /model.6/m.0/m/m.0/cv2/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_16_P_PIX  = 1;
  localparam int LAYER_16_P_COUT = 32;
  localparam int LAYER_16_P_CIN  = 1;
  localparam int LAYER_16_H      = 40;
  localparam int LAYER_16_W      = 40;
  localparam int LAYER_16_K      = 3;
  localparam int LAYER_16_CIN    = 32;
  localparam int LAYER_16_COUT   = 32;
  localparam int LAYER_16_STRIDE = 1;
  localparam int LAYER_16_PAD    = 1;
  localparam int LAYER_16_GROUP  = 1;
  localparam int LAYER_16_CYCLES = 51200;

  // L17: /model.6/m.0/m/m.1/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_17_P_PIX  = 1;
  localparam int LAYER_17_P_COUT = 32;
  localparam int LAYER_17_P_CIN  = 1;
  localparam int LAYER_17_H      = 40;
  localparam int LAYER_17_W      = 40;
  localparam int LAYER_17_K      = 3;
  localparam int LAYER_17_CIN    = 32;
  localparam int LAYER_17_COUT   = 32;
  localparam int LAYER_17_STRIDE = 1;
  localparam int LAYER_17_PAD    = 1;
  localparam int LAYER_17_GROUP  = 1;
  localparam int LAYER_17_CYCLES = 51200;

  // L18: /model.6/m.0/m/m.1/cv2/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_18_P_PIX  = 1;
  localparam int LAYER_18_P_COUT = 32;
  localparam int LAYER_18_P_CIN  = 1;
  localparam int LAYER_18_H      = 40;
  localparam int LAYER_18_W      = 40;
  localparam int LAYER_18_K      = 3;
  localparam int LAYER_18_CIN    = 32;
  localparam int LAYER_18_COUT   = 32;
  localparam int LAYER_18_STRIDE = 1;
  localparam int LAYER_18_PAD    = 1;
  localparam int LAYER_18_GROUP  = 1;
  localparam int LAYER_18_CYCLES = 51200;

  // L19: /model.6/m.0/cv3/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=6553600  cycles=51200  (target T=100000)
  localparam int LAYER_19_P_PIX  = 1;
  localparam int LAYER_19_P_COUT = 64;
  localparam int LAYER_19_P_CIN  = 2;
  localparam int LAYER_19_H      = 40;
  localparam int LAYER_19_W      = 40;
  localparam int LAYER_19_K      = 1;
  localparam int LAYER_19_CIN    = 64;
  localparam int LAYER_19_COUT   = 64;
  localparam int LAYER_19_STRIDE = 1;
  localparam int LAYER_19_PAD    = 0;
  localparam int LAYER_19_GROUP  = 1;
  localparam int LAYER_19_CYCLES = 51200;

  // L20: /model.6/cv2/conv/Conv_quant
  //   shape  Cin=192 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_20_P_PIX  = 1;
  localparam int LAYER_20_P_COUT = 128;
  localparam int LAYER_20_P_CIN  = 4;
  localparam int LAYER_20_H      = 40;
  localparam int LAYER_20_W      = 40;
  localparam int LAYER_20_K      = 1;
  localparam int LAYER_20_CIN    = 192;
  localparam int LAYER_20_COUT   = 128;
  localparam int LAYER_20_STRIDE = 1;
  localparam int LAYER_20_PAD    = 0;
  localparam int LAYER_20_GROUP  = 1;
  localparam int LAYER_20_CYCLES = 76800;

  // L21: /model.7/conv/Conv_quant
  //   shape  Cin=128 Cout=256 K=3 stride=2 pad=1 group=1
  //   H_in=40 W_in=40 H_out=20 W_out=20
  //   M=117964800  cycles=51200  (target T=100000)
  localparam int LAYER_21_P_PIX  = 1;
  localparam int LAYER_21_P_COUT = 256;
  localparam int LAYER_21_P_CIN  = 1;
  localparam int LAYER_21_H      = 20;
  localparam int LAYER_21_W      = 20;
  localparam int LAYER_21_K      = 3;
  localparam int LAYER_21_CIN    = 128;
  localparam int LAYER_21_COUT   = 256;
  localparam int LAYER_21_STRIDE = 2;
  localparam int LAYER_21_PAD    = 1;
  localparam int LAYER_21_GROUP  = 1;
  localparam int LAYER_21_CYCLES = 51200;

  // L22: /model.8/cv1/conv/Conv_quant
  //   shape  Cin=256 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=26214400  cycles=51200  (target T=100000)
  localparam int LAYER_22_P_PIX  = 1;
  localparam int LAYER_22_P_COUT = 256;
  localparam int LAYER_22_P_CIN  = 2;
  localparam int LAYER_22_H      = 20;
  localparam int LAYER_22_W      = 20;
  localparam int LAYER_22_K      = 1;
  localparam int LAYER_22_CIN    = 256;
  localparam int LAYER_22_COUT   = 256;
  localparam int LAYER_22_STRIDE = 1;
  localparam int LAYER_22_PAD    = 0;
  localparam int LAYER_22_GROUP  = 1;
  localparam int LAYER_22_CYCLES = 51200;

  // L23: /model.8/m.0/cv1/conv/Conv_quant
  //   shape  Cin=128 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_23_P_PIX  = 1;
  localparam int LAYER_23_P_COUT = 64;
  localparam int LAYER_23_P_CIN  = 1;
  localparam int LAYER_23_H      = 20;
  localparam int LAYER_23_W      = 20;
  localparam int LAYER_23_K      = 1;
  localparam int LAYER_23_CIN    = 128;
  localparam int LAYER_23_COUT   = 64;
  localparam int LAYER_23_STRIDE = 1;
  localparam int LAYER_23_PAD    = 0;
  localparam int LAYER_23_GROUP  = 1;
  localparam int LAYER_23_CYCLES = 51200;

  // L24: /model.8/m.0/cv2/conv/Conv_quant
  //   shape  Cin=128 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_24_P_PIX  = 1;
  localparam int LAYER_24_P_COUT = 64;
  localparam int LAYER_24_P_CIN  = 1;
  localparam int LAYER_24_H      = 20;
  localparam int LAYER_24_W      = 20;
  localparam int LAYER_24_K      = 1;
  localparam int LAYER_24_CIN    = 128;
  localparam int LAYER_24_COUT   = 64;
  localparam int LAYER_24_STRIDE = 1;
  localparam int LAYER_24_PAD    = 0;
  localparam int LAYER_24_GROUP  = 1;
  localparam int LAYER_24_CYCLES = 51200;

  // L25: /model.8/m.0/m/m.0/cv1/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_25_P_PIX  = 1;
  localparam int LAYER_25_P_COUT = 32;
  localparam int LAYER_25_P_CIN  = 1;
  localparam int LAYER_25_H      = 20;
  localparam int LAYER_25_W      = 20;
  localparam int LAYER_25_K      = 3;
  localparam int LAYER_25_CIN    = 64;
  localparam int LAYER_25_COUT   = 64;
  localparam int LAYER_25_STRIDE = 1;
  localparam int LAYER_25_PAD    = 1;
  localparam int LAYER_25_GROUP  = 1;
  localparam int LAYER_25_CYCLES = 51200;

  // L26: /model.8/m.0/m/m.0/cv2/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_26_P_PIX  = 1;
  localparam int LAYER_26_P_COUT = 32;
  localparam int LAYER_26_P_CIN  = 1;
  localparam int LAYER_26_H      = 20;
  localparam int LAYER_26_W      = 20;
  localparam int LAYER_26_K      = 3;
  localparam int LAYER_26_CIN    = 64;
  localparam int LAYER_26_COUT   = 64;
  localparam int LAYER_26_STRIDE = 1;
  localparam int LAYER_26_PAD    = 1;
  localparam int LAYER_26_GROUP  = 1;
  localparam int LAYER_26_CYCLES = 51200;

  // L27: /model.8/m.0/m/m.1/cv1/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_27_P_PIX  = 1;
  localparam int LAYER_27_P_COUT = 32;
  localparam int LAYER_27_P_CIN  = 1;
  localparam int LAYER_27_H      = 20;
  localparam int LAYER_27_W      = 20;
  localparam int LAYER_27_K      = 3;
  localparam int LAYER_27_CIN    = 64;
  localparam int LAYER_27_COUT   = 64;
  localparam int LAYER_27_STRIDE = 1;
  localparam int LAYER_27_PAD    = 1;
  localparam int LAYER_27_GROUP  = 1;
  localparam int LAYER_27_CYCLES = 51200;

  // L28: /model.8/m.0/m/m.1/cv2/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_28_P_PIX  = 1;
  localparam int LAYER_28_P_COUT = 32;
  localparam int LAYER_28_P_CIN  = 1;
  localparam int LAYER_28_H      = 20;
  localparam int LAYER_28_W      = 20;
  localparam int LAYER_28_K      = 3;
  localparam int LAYER_28_CIN    = 64;
  localparam int LAYER_28_COUT   = 64;
  localparam int LAYER_28_STRIDE = 1;
  localparam int LAYER_28_PAD    = 1;
  localparam int LAYER_28_GROUP  = 1;
  localparam int LAYER_28_CYCLES = 51200;

  // L29: /model.8/m.0/cv3/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=6553600  cycles=51200  (target T=100000)
  localparam int LAYER_29_P_PIX  = 1;
  localparam int LAYER_29_P_COUT = 128;
  localparam int LAYER_29_P_CIN  = 1;
  localparam int LAYER_29_H      = 20;
  localparam int LAYER_29_W      = 20;
  localparam int LAYER_29_K      = 1;
  localparam int LAYER_29_CIN    = 128;
  localparam int LAYER_29_COUT   = 128;
  localparam int LAYER_29_STRIDE = 1;
  localparam int LAYER_29_PAD    = 0;
  localparam int LAYER_29_GROUP  = 1;
  localparam int LAYER_29_CYCLES = 51200;

  // L30: /model.8/cv2/conv/Conv_quant
  //   shape  Cin=384 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_30_P_PIX  = 1;
  localparam int LAYER_30_P_COUT = 256;
  localparam int LAYER_30_P_CIN  = 2;
  localparam int LAYER_30_H      = 20;
  localparam int LAYER_30_W      = 20;
  localparam int LAYER_30_K      = 1;
  localparam int LAYER_30_CIN    = 384;
  localparam int LAYER_30_COUT   = 256;
  localparam int LAYER_30_STRIDE = 1;
  localparam int LAYER_30_PAD    = 0;
  localparam int LAYER_30_GROUP  = 1;
  localparam int LAYER_30_CYCLES = 76800;

  // L31: /model.9/cv1/conv/Conv_quant
  //   shape  Cin=256 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=13107200  cycles=51200  (target T=100000)
  localparam int LAYER_31_P_PIX  = 1;
  localparam int LAYER_31_P_COUT = 128;
  localparam int LAYER_31_P_CIN  = 2;
  localparam int LAYER_31_H      = 20;
  localparam int LAYER_31_W      = 20;
  localparam int LAYER_31_K      = 1;
  localparam int LAYER_31_CIN    = 256;
  localparam int LAYER_31_COUT   = 128;
  localparam int LAYER_31_STRIDE = 1;
  localparam int LAYER_31_PAD    = 0;
  localparam int LAYER_31_GROUP  = 1;
  localparam int LAYER_31_CYCLES = 51200;

  // L32: /model.9/cv2/conv/Conv_quant
  //   shape  Cin=512 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=52428800  cycles=51200  (target T=100000)
  localparam int LAYER_32_P_PIX  = 1;
  localparam int LAYER_32_P_COUT = 256;
  localparam int LAYER_32_P_CIN  = 4;
  localparam int LAYER_32_H      = 20;
  localparam int LAYER_32_W      = 20;
  localparam int LAYER_32_K      = 1;
  localparam int LAYER_32_CIN    = 512;
  localparam int LAYER_32_COUT   = 256;
  localparam int LAYER_32_STRIDE = 1;
  localparam int LAYER_32_PAD    = 0;
  localparam int LAYER_32_GROUP  = 1;
  localparam int LAYER_32_CYCLES = 51200;

  // L33: /model.10/cv1/conv/Conv_quant
  //   shape  Cin=256 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=26214400  cycles=51200  (target T=100000)
  localparam int LAYER_33_P_PIX  = 1;
  localparam int LAYER_33_P_COUT = 256;
  localparam int LAYER_33_P_CIN  = 2;
  localparam int LAYER_33_H      = 20;
  localparam int LAYER_33_W      = 20;
  localparam int LAYER_33_K      = 1;
  localparam int LAYER_33_CIN    = 256;
  localparam int LAYER_33_COUT   = 256;
  localparam int LAYER_33_STRIDE = 1;
  localparam int LAYER_33_PAD    = 0;
  localparam int LAYER_33_GROUP  = 1;
  localparam int LAYER_33_CYCLES = 51200;

  // L34: /model.10/m/m.0/attn/qkv/conv/Conv_quant
  //   shape  Cin=128 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=13107200  cycles=51200  (target T=100000)
  localparam int LAYER_34_P_PIX  = 1;
  localparam int LAYER_34_P_COUT = 256;
  localparam int LAYER_34_P_CIN  = 1;
  localparam int LAYER_34_H      = 20;
  localparam int LAYER_34_W      = 20;
  localparam int LAYER_34_K      = 1;
  localparam int LAYER_34_CIN    = 128;
  localparam int LAYER_34_COUT   = 256;
  localparam int LAYER_34_STRIDE = 1;
  localparam int LAYER_34_PAD    = 0;
  localparam int LAYER_34_GROUP  = 1;
  localparam int LAYER_34_CYCLES = 51200;

  // L35: /model.10/m/m.0/attn/pe/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=3 stride=1 pad=1 group=128
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=58982400  cycles=51200  (target T=100000)
  localparam int LAYER_35_P_PIX  = 1;
  localparam int LAYER_35_P_COUT = 128;
  localparam int LAYER_35_P_CIN  = 1;
  localparam int LAYER_35_H      = 20;
  localparam int LAYER_35_W      = 20;
  localparam int LAYER_35_K      = 3;
  localparam int LAYER_35_CIN    = 128;
  localparam int LAYER_35_COUT   = 128;
  localparam int LAYER_35_STRIDE = 1;
  localparam int LAYER_35_PAD    = 1;
  localparam int LAYER_35_GROUP  = 128;
  localparam int LAYER_35_CYCLES = 51200;

  // L36: /model.10/m/m.0/attn/proj/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=6553600  cycles=51200  (target T=100000)
  localparam int LAYER_36_P_PIX  = 1;
  localparam int LAYER_36_P_COUT = 128;
  localparam int LAYER_36_P_CIN  = 1;
  localparam int LAYER_36_H      = 20;
  localparam int LAYER_36_W      = 20;
  localparam int LAYER_36_K      = 1;
  localparam int LAYER_36_CIN    = 128;
  localparam int LAYER_36_COUT   = 128;
  localparam int LAYER_36_STRIDE = 1;
  localparam int LAYER_36_PAD    = 0;
  localparam int LAYER_36_GROUP  = 1;
  localparam int LAYER_36_CYCLES = 51200;

  // L37: /model.10/m/m.0/ffn/ffn.0/conv/Conv_quant
  //   shape  Cin=128 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=13107200  cycles=51200  (target T=100000)
  localparam int LAYER_37_P_PIX  = 1;
  localparam int LAYER_37_P_COUT = 256;
  localparam int LAYER_37_P_CIN  = 1;
  localparam int LAYER_37_H      = 20;
  localparam int LAYER_37_W      = 20;
  localparam int LAYER_37_K      = 1;
  localparam int LAYER_37_CIN    = 128;
  localparam int LAYER_37_COUT   = 256;
  localparam int LAYER_37_STRIDE = 1;
  localparam int LAYER_37_PAD    = 0;
  localparam int LAYER_37_GROUP  = 1;
  localparam int LAYER_37_CYCLES = 51200;

  // L38: /model.10/m/m.0/ffn/ffn.1/conv/Conv_quant
  //   shape  Cin=256 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=13107200  cycles=51200  (target T=100000)
  localparam int LAYER_38_P_PIX  = 1;
  localparam int LAYER_38_P_COUT = 128;
  localparam int LAYER_38_P_CIN  = 2;
  localparam int LAYER_38_H      = 20;
  localparam int LAYER_38_W      = 20;
  localparam int LAYER_38_K      = 1;
  localparam int LAYER_38_CIN    = 256;
  localparam int LAYER_38_COUT   = 128;
  localparam int LAYER_38_STRIDE = 1;
  localparam int LAYER_38_PAD    = 0;
  localparam int LAYER_38_GROUP  = 1;
  localparam int LAYER_38_CYCLES = 51200;

  // L39: /model.10/cv2/conv/Conv_quant
  //   shape  Cin=256 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=26214400  cycles=51200  (target T=100000)
  localparam int LAYER_39_P_PIX  = 1;
  localparam int LAYER_39_P_COUT = 256;
  localparam int LAYER_39_P_CIN  = 2;
  localparam int LAYER_39_H      = 20;
  localparam int LAYER_39_W      = 20;
  localparam int LAYER_39_K      = 1;
  localparam int LAYER_39_CIN    = 256;
  localparam int LAYER_39_COUT   = 256;
  localparam int LAYER_39_STRIDE = 1;
  localparam int LAYER_39_PAD    = 0;
  localparam int LAYER_39_GROUP  = 1;
  localparam int LAYER_39_CYCLES = 51200;

  // L40: /model.13/cv1/conv/Conv_quant
  //   shape  Cin=384 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=78643200  cycles=76800  (target T=100000)
  localparam int LAYER_40_P_PIX  = 1;
  localparam int LAYER_40_P_COUT = 128;
  localparam int LAYER_40_P_CIN  = 8;
  localparam int LAYER_40_H      = 40;
  localparam int LAYER_40_W      = 40;
  localparam int LAYER_40_K      = 1;
  localparam int LAYER_40_CIN    = 384;
  localparam int LAYER_40_COUT   = 128;
  localparam int LAYER_40_STRIDE = 1;
  localparam int LAYER_40_PAD    = 0;
  localparam int LAYER_40_GROUP  = 1;
  localparam int LAYER_40_CYCLES = 76800;

  // L41: /model.13/m.0/cv1/conv/Conv_quant
  //   shape  Cin=64 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_41_P_PIX  = 1;
  localparam int LAYER_41_P_COUT = 32;
  localparam int LAYER_41_P_CIN  = 2;
  localparam int LAYER_41_H      = 40;
  localparam int LAYER_41_W      = 40;
  localparam int LAYER_41_K      = 1;
  localparam int LAYER_41_CIN    = 64;
  localparam int LAYER_41_COUT   = 32;
  localparam int LAYER_41_STRIDE = 1;
  localparam int LAYER_41_PAD    = 0;
  localparam int LAYER_41_GROUP  = 1;
  localparam int LAYER_41_CYCLES = 51200;

  // L42: /model.13/m.0/cv2/conv/Conv_quant
  //   shape  Cin=64 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_42_P_PIX  = 1;
  localparam int LAYER_42_P_COUT = 32;
  localparam int LAYER_42_P_CIN  = 2;
  localparam int LAYER_42_H      = 40;
  localparam int LAYER_42_W      = 40;
  localparam int LAYER_42_K      = 1;
  localparam int LAYER_42_CIN    = 64;
  localparam int LAYER_42_COUT   = 32;
  localparam int LAYER_42_STRIDE = 1;
  localparam int LAYER_42_PAD    = 0;
  localparam int LAYER_42_GROUP  = 1;
  localparam int LAYER_42_CYCLES = 51200;

  // L43: /model.13/m.0/m/m.0/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_43_P_PIX  = 1;
  localparam int LAYER_43_P_COUT = 32;
  localparam int LAYER_43_P_CIN  = 1;
  localparam int LAYER_43_H      = 40;
  localparam int LAYER_43_W      = 40;
  localparam int LAYER_43_K      = 3;
  localparam int LAYER_43_CIN    = 32;
  localparam int LAYER_43_COUT   = 32;
  localparam int LAYER_43_STRIDE = 1;
  localparam int LAYER_43_PAD    = 1;
  localparam int LAYER_43_GROUP  = 1;
  localparam int LAYER_43_CYCLES = 51200;

  // L44: /model.13/m.0/m/m.0/cv2/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_44_P_PIX  = 1;
  localparam int LAYER_44_P_COUT = 32;
  localparam int LAYER_44_P_CIN  = 1;
  localparam int LAYER_44_H      = 40;
  localparam int LAYER_44_W      = 40;
  localparam int LAYER_44_K      = 3;
  localparam int LAYER_44_CIN    = 32;
  localparam int LAYER_44_COUT   = 32;
  localparam int LAYER_44_STRIDE = 1;
  localparam int LAYER_44_PAD    = 1;
  localparam int LAYER_44_GROUP  = 1;
  localparam int LAYER_44_CYCLES = 51200;

  // L45: /model.13/m.0/m/m.1/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_45_P_PIX  = 1;
  localparam int LAYER_45_P_COUT = 32;
  localparam int LAYER_45_P_CIN  = 1;
  localparam int LAYER_45_H      = 40;
  localparam int LAYER_45_W      = 40;
  localparam int LAYER_45_K      = 3;
  localparam int LAYER_45_CIN    = 32;
  localparam int LAYER_45_COUT   = 32;
  localparam int LAYER_45_STRIDE = 1;
  localparam int LAYER_45_PAD    = 1;
  localparam int LAYER_45_GROUP  = 1;
  localparam int LAYER_45_CYCLES = 51200;

  // L46: /model.13/m.0/m/m.1/cv2/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_46_P_PIX  = 1;
  localparam int LAYER_46_P_COUT = 32;
  localparam int LAYER_46_P_CIN  = 1;
  localparam int LAYER_46_H      = 40;
  localparam int LAYER_46_W      = 40;
  localparam int LAYER_46_K      = 3;
  localparam int LAYER_46_CIN    = 32;
  localparam int LAYER_46_COUT   = 32;
  localparam int LAYER_46_STRIDE = 1;
  localparam int LAYER_46_PAD    = 1;
  localparam int LAYER_46_GROUP  = 1;
  localparam int LAYER_46_CYCLES = 51200;

  // L47: /model.13/m.0/cv3/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=6553600  cycles=51200  (target T=100000)
  localparam int LAYER_47_P_PIX  = 1;
  localparam int LAYER_47_P_COUT = 64;
  localparam int LAYER_47_P_CIN  = 2;
  localparam int LAYER_47_H      = 40;
  localparam int LAYER_47_W      = 40;
  localparam int LAYER_47_K      = 1;
  localparam int LAYER_47_CIN    = 64;
  localparam int LAYER_47_COUT   = 64;
  localparam int LAYER_47_STRIDE = 1;
  localparam int LAYER_47_PAD    = 0;
  localparam int LAYER_47_GROUP  = 1;
  localparam int LAYER_47_CYCLES = 51200;

  // L48: /model.13/cv2/conv/Conv_quant
  //   shape  Cin=192 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_48_P_PIX  = 1;
  localparam int LAYER_48_P_COUT = 128;
  localparam int LAYER_48_P_CIN  = 4;
  localparam int LAYER_48_H      = 40;
  localparam int LAYER_48_W      = 40;
  localparam int LAYER_48_K      = 1;
  localparam int LAYER_48_CIN    = 192;
  localparam int LAYER_48_COUT   = 128;
  localparam int LAYER_48_STRIDE = 1;
  localparam int LAYER_48_PAD    = 0;
  localparam int LAYER_48_GROUP  = 1;
  localparam int LAYER_48_CYCLES = 76800;

  // L49: /model.16/cv1/conv/Conv_quant
  //   shape  Cin=256 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=104857600  cycles=51200  (target T=100000)
  localparam int LAYER_49_P_PIX  = 1;
  localparam int LAYER_49_P_COUT = 64;
  localparam int LAYER_49_P_CIN  = 32;
  localparam int LAYER_49_H      = 80;
  localparam int LAYER_49_W      = 80;
  localparam int LAYER_49_K      = 1;
  localparam int LAYER_49_CIN    = 256;
  localparam int LAYER_49_COUT   = 64;
  localparam int LAYER_49_STRIDE = 1;
  localparam int LAYER_49_PAD    = 0;
  localparam int LAYER_49_GROUP  = 1;
  localparam int LAYER_49_CYCLES = 51200;

  // L50: /model.16/m.0/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=16 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_50_P_PIX  = 1;
  localparam int LAYER_50_P_COUT = 16;
  localparam int LAYER_50_P_CIN  = 4;
  localparam int LAYER_50_H      = 80;
  localparam int LAYER_50_W      = 80;
  localparam int LAYER_50_K      = 1;
  localparam int LAYER_50_CIN    = 32;
  localparam int LAYER_50_COUT   = 16;
  localparam int LAYER_50_STRIDE = 1;
  localparam int LAYER_50_PAD    = 0;
  localparam int LAYER_50_GROUP  = 1;
  localparam int LAYER_50_CYCLES = 51200;

  // L51: /model.16/m.0/cv2/conv/Conv_quant
  //   shape  Cin=32 Cout=16 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_51_P_PIX  = 1;
  localparam int LAYER_51_P_COUT = 16;
  localparam int LAYER_51_P_CIN  = 4;
  localparam int LAYER_51_H      = 80;
  localparam int LAYER_51_W      = 80;
  localparam int LAYER_51_K      = 1;
  localparam int LAYER_51_CIN    = 32;
  localparam int LAYER_51_COUT   = 16;
  localparam int LAYER_51_STRIDE = 1;
  localparam int LAYER_51_PAD    = 0;
  localparam int LAYER_51_GROUP  = 1;
  localparam int LAYER_51_CYCLES = 51200;

  // L52: /model.16/m.0/m/m.0/cv1/conv/Conv_quant
  //   shape  Cin=16 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_52_P_PIX  = 1;
  localparam int LAYER_52_P_COUT = 16;
  localparam int LAYER_52_P_CIN  = 2;
  localparam int LAYER_52_H      = 80;
  localparam int LAYER_52_W      = 80;
  localparam int LAYER_52_K      = 3;
  localparam int LAYER_52_CIN    = 16;
  localparam int LAYER_52_COUT   = 16;
  localparam int LAYER_52_STRIDE = 1;
  localparam int LAYER_52_PAD    = 1;
  localparam int LAYER_52_GROUP  = 1;
  localparam int LAYER_52_CYCLES = 51200;

  // L53: /model.16/m.0/m/m.0/cv2/conv/Conv_quant
  //   shape  Cin=16 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_53_P_PIX  = 1;
  localparam int LAYER_53_P_COUT = 16;
  localparam int LAYER_53_P_CIN  = 2;
  localparam int LAYER_53_H      = 80;
  localparam int LAYER_53_W      = 80;
  localparam int LAYER_53_K      = 3;
  localparam int LAYER_53_CIN    = 16;
  localparam int LAYER_53_COUT   = 16;
  localparam int LAYER_53_STRIDE = 1;
  localparam int LAYER_53_PAD    = 1;
  localparam int LAYER_53_GROUP  = 1;
  localparam int LAYER_53_CYCLES = 51200;

  // L54: /model.16/m.0/m/m.1/cv1/conv/Conv_quant
  //   shape  Cin=16 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_54_P_PIX  = 1;
  localparam int LAYER_54_P_COUT = 16;
  localparam int LAYER_54_P_CIN  = 2;
  localparam int LAYER_54_H      = 80;
  localparam int LAYER_54_W      = 80;
  localparam int LAYER_54_K      = 3;
  localparam int LAYER_54_CIN    = 16;
  localparam int LAYER_54_COUT   = 16;
  localparam int LAYER_54_STRIDE = 1;
  localparam int LAYER_54_PAD    = 1;
  localparam int LAYER_54_GROUP  = 1;
  localparam int LAYER_54_CYCLES = 51200;

  // L55: /model.16/m.0/m/m.1/cv2/conv/Conv_quant
  //   shape  Cin=16 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_55_P_PIX  = 1;
  localparam int LAYER_55_P_COUT = 16;
  localparam int LAYER_55_P_CIN  = 2;
  localparam int LAYER_55_H      = 80;
  localparam int LAYER_55_W      = 80;
  localparam int LAYER_55_K      = 3;
  localparam int LAYER_55_CIN    = 16;
  localparam int LAYER_55_COUT   = 16;
  localparam int LAYER_55_STRIDE = 1;
  localparam int LAYER_55_PAD    = 1;
  localparam int LAYER_55_GROUP  = 1;
  localparam int LAYER_55_CYCLES = 51200;

  // L56: /model.16/m.0/cv3/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=6553600  cycles=51200  (target T=100000)
  localparam int LAYER_56_P_PIX  = 1;
  localparam int LAYER_56_P_COUT = 32;
  localparam int LAYER_56_P_CIN  = 4;
  localparam int LAYER_56_H      = 80;
  localparam int LAYER_56_W      = 80;
  localparam int LAYER_56_K      = 1;
  localparam int LAYER_56_CIN    = 32;
  localparam int LAYER_56_COUT   = 32;
  localparam int LAYER_56_STRIDE = 1;
  localparam int LAYER_56_PAD    = 0;
  localparam int LAYER_56_GROUP  = 1;
  localparam int LAYER_56_CYCLES = 51200;

  // L57: /model.16/cv2/conv/Conv_quant
  //   shape  Cin=96 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_57_P_PIX  = 1;
  localparam int LAYER_57_P_COUT = 64;
  localparam int LAYER_57_P_CIN  = 8;
  localparam int LAYER_57_H      = 80;
  localparam int LAYER_57_W      = 80;
  localparam int LAYER_57_K      = 1;
  localparam int LAYER_57_CIN    = 96;
  localparam int LAYER_57_COUT   = 64;
  localparam int LAYER_57_STRIDE = 1;
  localparam int LAYER_57_PAD    = 0;
  localparam int LAYER_57_GROUP  = 1;
  localparam int LAYER_57_CYCLES = 76800;

  // L58: /model.17/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=3 stride=2 pad=1 group=1
  //   H_in=80 W_in=80 H_out=40 W_out=40
  //   M=58982400  cycles=51200  (target T=100000)
  localparam int LAYER_58_P_PIX  = 1;
  localparam int LAYER_58_P_COUT = 64;
  localparam int LAYER_58_P_CIN  = 2;
  localparam int LAYER_58_H      = 40;
  localparam int LAYER_58_W      = 40;
  localparam int LAYER_58_K      = 3;
  localparam int LAYER_58_CIN    = 64;
  localparam int LAYER_58_COUT   = 64;
  localparam int LAYER_58_STRIDE = 2;
  localparam int LAYER_58_PAD    = 1;
  localparam int LAYER_58_GROUP  = 1;
  localparam int LAYER_58_CYCLES = 51200;

  // L59: /model.23/one2one_cv2.0/one2one_cv2.0.0/conv/Conv_quant
  //   shape  Cin=64 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=58982400  cycles=51200  (target T=100000)
  localparam int LAYER_59_P_PIX  = 1;
  localparam int LAYER_59_P_COUT = 16;
  localparam int LAYER_59_P_CIN  = 8;
  localparam int LAYER_59_H      = 80;
  localparam int LAYER_59_W      = 80;
  localparam int LAYER_59_K      = 3;
  localparam int LAYER_59_CIN    = 64;
  localparam int LAYER_59_COUT   = 16;
  localparam int LAYER_59_STRIDE = 1;
  localparam int LAYER_59_PAD    = 1;
  localparam int LAYER_59_GROUP  = 1;
  localparam int LAYER_59_CYCLES = 51200;

  // L60: /model.23/one2one_cv3.0/one2one_cv3.0.0/one2one_cv3.0.0.0/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=3 stride=1 pad=1 group=64
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=235929600  cycles=51200  (target T=100000)
  localparam int LAYER_60_P_PIX  = 1;
  localparam int LAYER_60_P_COUT = 64;
  localparam int LAYER_60_P_CIN  = 8;
  localparam int LAYER_60_H      = 80;
  localparam int LAYER_60_W      = 80;
  localparam int LAYER_60_K      = 3;
  localparam int LAYER_60_CIN    = 64;
  localparam int LAYER_60_COUT   = 64;
  localparam int LAYER_60_STRIDE = 1;
  localparam int LAYER_60_PAD    = 1;
  localparam int LAYER_60_GROUP  = 64;
  localparam int LAYER_60_CYCLES = 51200;

  // L61: /model.23/one2one_cv2.0/one2one_cv2.0.1/conv/Conv_quant
  //   shape  Cin=16 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_61_P_PIX  = 1;
  localparam int LAYER_61_P_COUT = 16;
  localparam int LAYER_61_P_CIN  = 2;
  localparam int LAYER_61_H      = 80;
  localparam int LAYER_61_W      = 80;
  localparam int LAYER_61_K      = 3;
  localparam int LAYER_61_CIN    = 16;
  localparam int LAYER_61_COUT   = 16;
  localparam int LAYER_61_STRIDE = 1;
  localparam int LAYER_61_PAD    = 1;
  localparam int LAYER_61_GROUP  = 1;
  localparam int LAYER_61_CYCLES = 51200;

  // L62: /model.23/one2one_cv3.0/one2one_cv3.0.0/one2one_cv3.0.0.1/conv/Conv_quant
  //   shape  Cin=64 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=32768000  cycles=51200  (target T=100000)
  localparam int LAYER_62_P_PIX  = 1;
  localparam int LAYER_62_P_COUT = 80;
  localparam int LAYER_62_P_CIN  = 8;
  localparam int LAYER_62_H      = 80;
  localparam int LAYER_62_W      = 80;
  localparam int LAYER_62_K      = 1;
  localparam int LAYER_62_CIN    = 64;
  localparam int LAYER_62_COUT   = 80;
  localparam int LAYER_62_STRIDE = 1;
  localparam int LAYER_62_PAD    = 0;
  localparam int LAYER_62_GROUP  = 1;
  localparam int LAYER_62_CYCLES = 51200;

  // L63: /model.19/cv1/conv/Conv_quant
  //   shape  Cin=192 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_63_P_PIX  = 1;
  localparam int LAYER_63_P_COUT = 128;
  localparam int LAYER_63_P_CIN  = 4;
  localparam int LAYER_63_H      = 40;
  localparam int LAYER_63_W      = 40;
  localparam int LAYER_63_K      = 1;
  localparam int LAYER_63_CIN    = 192;
  localparam int LAYER_63_COUT   = 128;
  localparam int LAYER_63_STRIDE = 1;
  localparam int LAYER_63_PAD    = 0;
  localparam int LAYER_63_GROUP  = 1;
  localparam int LAYER_63_CYCLES = 76800;

  // L64: /model.23/one2one_cv2.0/one2one_cv2.0.2/Conv_quant
  //   shape  Cin=16 Cout=4 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=409600  cycles=51200  (target T=100000)
  localparam int LAYER_64_P_PIX  = 1;
  localparam int LAYER_64_P_COUT = 4;
  localparam int LAYER_64_P_CIN  = 2;
  localparam int LAYER_64_H      = 80;
  localparam int LAYER_64_W      = 80;
  localparam int LAYER_64_K      = 1;
  localparam int LAYER_64_CIN    = 16;
  localparam int LAYER_64_COUT   = 4;
  localparam int LAYER_64_STRIDE = 1;
  localparam int LAYER_64_PAD    = 0;
  localparam int LAYER_64_GROUP  = 1;
  localparam int LAYER_64_CYCLES = 51200;

  // L65: /model.23/one2one_cv3.0/one2one_cv3.0.1/one2one_cv3.0.1.0/conv/Conv_quant
  //   shape  Cin=80 Cout=80 K=3 stride=1 pad=1 group=80
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=368640000  cycles=64000  (target T=100000)
  localparam int LAYER_65_P_PIX  = 1;
  localparam int LAYER_65_P_COUT = 80;
  localparam int LAYER_65_P_CIN  = 8;
  localparam int LAYER_65_H      = 80;
  localparam int LAYER_65_W      = 80;
  localparam int LAYER_65_K      = 3;
  localparam int LAYER_65_CIN    = 80;
  localparam int LAYER_65_COUT   = 80;
  localparam int LAYER_65_STRIDE = 1;
  localparam int LAYER_65_PAD    = 1;
  localparam int LAYER_65_GROUP  = 80;
  localparam int LAYER_65_CYCLES = 64000;

  // L66: /model.19/m.0/cv1/conv/Conv_quant
  //   shape  Cin=64 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_66_P_PIX  = 1;
  localparam int LAYER_66_P_COUT = 32;
  localparam int LAYER_66_P_CIN  = 2;
  localparam int LAYER_66_H      = 40;
  localparam int LAYER_66_W      = 40;
  localparam int LAYER_66_K      = 1;
  localparam int LAYER_66_CIN    = 64;
  localparam int LAYER_66_COUT   = 32;
  localparam int LAYER_66_STRIDE = 1;
  localparam int LAYER_66_PAD    = 0;
  localparam int LAYER_66_GROUP  = 1;
  localparam int LAYER_66_CYCLES = 51200;

  // L67: /model.19/m.0/cv2/conv/Conv_quant
  //   shape  Cin=64 Cout=32 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=3276800  cycles=51200  (target T=100000)
  localparam int LAYER_67_P_PIX  = 1;
  localparam int LAYER_67_P_COUT = 32;
  localparam int LAYER_67_P_CIN  = 2;
  localparam int LAYER_67_H      = 40;
  localparam int LAYER_67_W      = 40;
  localparam int LAYER_67_K      = 1;
  localparam int LAYER_67_CIN    = 64;
  localparam int LAYER_67_COUT   = 32;
  localparam int LAYER_67_STRIDE = 1;
  localparam int LAYER_67_PAD    = 0;
  localparam int LAYER_67_GROUP  = 1;
  localparam int LAYER_67_CYCLES = 51200;

  // L68: /model.23/one2one_cv3.0/one2one_cv3.0.1/one2one_cv3.0.1.1/conv/Conv_quant
  //   shape  Cin=80 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=40960000  cycles=64000  (target T=100000)
  localparam int LAYER_68_P_PIX  = 1;
  localparam int LAYER_68_P_COUT = 80;
  localparam int LAYER_68_P_CIN  = 8;
  localparam int LAYER_68_H      = 80;
  localparam int LAYER_68_W      = 80;
  localparam int LAYER_68_K      = 1;
  localparam int LAYER_68_CIN    = 80;
  localparam int LAYER_68_COUT   = 80;
  localparam int LAYER_68_STRIDE = 1;
  localparam int LAYER_68_PAD    = 0;
  localparam int LAYER_68_GROUP  = 1;
  localparam int LAYER_68_CYCLES = 64000;

  // L69: /model.19/m.0/m/m.0/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_69_P_PIX  = 1;
  localparam int LAYER_69_P_COUT = 32;
  localparam int LAYER_69_P_CIN  = 1;
  localparam int LAYER_69_H      = 40;
  localparam int LAYER_69_W      = 40;
  localparam int LAYER_69_K      = 3;
  localparam int LAYER_69_CIN    = 32;
  localparam int LAYER_69_COUT   = 32;
  localparam int LAYER_69_STRIDE = 1;
  localparam int LAYER_69_PAD    = 1;
  localparam int LAYER_69_GROUP  = 1;
  localparam int LAYER_69_CYCLES = 51200;

  // L70: /model.23/one2one_cv3.0/one2one_cv3.0.2/Conv_quant
  //   shape  Cin=80 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=80 W_in=80 H_out=80 W_out=80
  //   M=40960000  cycles=64000  (target T=100000)
  localparam int LAYER_70_P_PIX  = 1;
  localparam int LAYER_70_P_COUT = 80;
  localparam int LAYER_70_P_CIN  = 8;
  localparam int LAYER_70_H      = 80;
  localparam int LAYER_70_W      = 80;
  localparam int LAYER_70_K      = 1;
  localparam int LAYER_70_CIN    = 80;
  localparam int LAYER_70_COUT   = 80;
  localparam int LAYER_70_STRIDE = 1;
  localparam int LAYER_70_PAD    = 0;
  localparam int LAYER_70_GROUP  = 1;
  localparam int LAYER_70_CYCLES = 64000;

  // L71: /model.19/m.0/m/m.0/cv2/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_71_P_PIX  = 1;
  localparam int LAYER_71_P_COUT = 32;
  localparam int LAYER_71_P_CIN  = 1;
  localparam int LAYER_71_H      = 40;
  localparam int LAYER_71_W      = 40;
  localparam int LAYER_71_K      = 3;
  localparam int LAYER_71_CIN    = 32;
  localparam int LAYER_71_COUT   = 32;
  localparam int LAYER_71_STRIDE = 1;
  localparam int LAYER_71_PAD    = 1;
  localparam int LAYER_71_GROUP  = 1;
  localparam int LAYER_71_CYCLES = 51200;

  // L72: /model.19/m.0/m/m.1/cv1/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_72_P_PIX  = 1;
  localparam int LAYER_72_P_COUT = 32;
  localparam int LAYER_72_P_CIN  = 1;
  localparam int LAYER_72_H      = 40;
  localparam int LAYER_72_W      = 40;
  localparam int LAYER_72_K      = 3;
  localparam int LAYER_72_CIN    = 32;
  localparam int LAYER_72_COUT   = 32;
  localparam int LAYER_72_STRIDE = 1;
  localparam int LAYER_72_PAD    = 1;
  localparam int LAYER_72_GROUP  = 1;
  localparam int LAYER_72_CYCLES = 51200;

  // L73: /model.19/m.0/m/m.1/cv2/conv/Conv_quant
  //   shape  Cin=32 Cout=32 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_73_P_PIX  = 1;
  localparam int LAYER_73_P_COUT = 32;
  localparam int LAYER_73_P_CIN  = 1;
  localparam int LAYER_73_H      = 40;
  localparam int LAYER_73_W      = 40;
  localparam int LAYER_73_K      = 3;
  localparam int LAYER_73_CIN    = 32;
  localparam int LAYER_73_COUT   = 32;
  localparam int LAYER_73_STRIDE = 1;
  localparam int LAYER_73_PAD    = 1;
  localparam int LAYER_73_GROUP  = 1;
  localparam int LAYER_73_CYCLES = 51200;

  // L74: /model.19/m.0/cv3/conv/Conv_quant
  //   shape  Cin=64 Cout=64 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=6553600  cycles=51200  (target T=100000)
  localparam int LAYER_74_P_PIX  = 1;
  localparam int LAYER_74_P_COUT = 64;
  localparam int LAYER_74_P_CIN  = 2;
  localparam int LAYER_74_H      = 40;
  localparam int LAYER_74_W      = 40;
  localparam int LAYER_74_K      = 1;
  localparam int LAYER_74_CIN    = 64;
  localparam int LAYER_74_COUT   = 64;
  localparam int LAYER_74_STRIDE = 1;
  localparam int LAYER_74_PAD    = 0;
  localparam int LAYER_74_GROUP  = 1;
  localparam int LAYER_74_CYCLES = 51200;

  // L75: /model.19/cv2/conv/Conv_quant
  //   shape  Cin=192 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_75_P_PIX  = 1;
  localparam int LAYER_75_P_COUT = 128;
  localparam int LAYER_75_P_CIN  = 4;
  localparam int LAYER_75_H      = 40;
  localparam int LAYER_75_W      = 40;
  localparam int LAYER_75_K      = 1;
  localparam int LAYER_75_CIN    = 192;
  localparam int LAYER_75_COUT   = 128;
  localparam int LAYER_75_STRIDE = 1;
  localparam int LAYER_75_PAD    = 0;
  localparam int LAYER_75_GROUP  = 1;
  localparam int LAYER_75_CYCLES = 76800;

  // L76: /model.20/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=3 stride=2 pad=1 group=1
  //   H_in=40 W_in=40 H_out=20 W_out=20
  //   M=58982400  cycles=51200  (target T=100000)
  localparam int LAYER_76_P_PIX  = 1;
  localparam int LAYER_76_P_COUT = 128;
  localparam int LAYER_76_P_CIN  = 1;
  localparam int LAYER_76_H      = 20;
  localparam int LAYER_76_W      = 20;
  localparam int LAYER_76_K      = 3;
  localparam int LAYER_76_CIN    = 128;
  localparam int LAYER_76_COUT   = 128;
  localparam int LAYER_76_STRIDE = 2;
  localparam int LAYER_76_PAD    = 1;
  localparam int LAYER_76_GROUP  = 1;
  localparam int LAYER_76_CYCLES = 51200;

  // L77: /model.23/one2one_cv2.1/one2one_cv2.1.0/conv/Conv_quant
  //   shape  Cin=128 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=29491200  cycles=51200  (target T=100000)
  localparam int LAYER_77_P_PIX  = 1;
  localparam int LAYER_77_P_COUT = 16;
  localparam int LAYER_77_P_CIN  = 4;
  localparam int LAYER_77_H      = 40;
  localparam int LAYER_77_W      = 40;
  localparam int LAYER_77_K      = 3;
  localparam int LAYER_77_CIN    = 128;
  localparam int LAYER_77_COUT   = 16;
  localparam int LAYER_77_STRIDE = 1;
  localparam int LAYER_77_PAD    = 1;
  localparam int LAYER_77_GROUP  = 1;
  localparam int LAYER_77_CYCLES = 51200;

  // L78: /model.23/one2one_cv3.1/one2one_cv3.1.0/one2one_cv3.1.0.0/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=3 stride=1 pad=1 group=128
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=235929600  cycles=51200  (target T=100000)
  localparam int LAYER_78_P_PIX  = 1;
  localparam int LAYER_78_P_COUT = 128;
  localparam int LAYER_78_P_CIN  = 4;
  localparam int LAYER_78_H      = 40;
  localparam int LAYER_78_W      = 40;
  localparam int LAYER_78_K      = 3;
  localparam int LAYER_78_CIN    = 128;
  localparam int LAYER_78_COUT   = 128;
  localparam int LAYER_78_STRIDE = 1;
  localparam int LAYER_78_PAD    = 1;
  localparam int LAYER_78_GROUP  = 128;
  localparam int LAYER_78_CYCLES = 51200;

  // L79: /model.23/one2one_cv2.1/one2one_cv2.1.1/conv/Conv_quant
  //   shape  Cin=16 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=3686400  cycles=51200  (target T=100000)
  localparam int LAYER_79_P_PIX  = 1;
  localparam int LAYER_79_P_COUT = 8;
  localparam int LAYER_79_P_CIN  = 1;
  localparam int LAYER_79_H      = 40;
  localparam int LAYER_79_W      = 40;
  localparam int LAYER_79_K      = 3;
  localparam int LAYER_79_CIN    = 16;
  localparam int LAYER_79_COUT   = 16;
  localparam int LAYER_79_STRIDE = 1;
  localparam int LAYER_79_PAD    = 1;
  localparam int LAYER_79_GROUP  = 1;
  localparam int LAYER_79_CYCLES = 51200;

  // L80: /model.23/one2one_cv3.1/one2one_cv3.1.0/one2one_cv3.1.0.1/conv/Conv_quant
  //   shape  Cin=128 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=16384000  cycles=51200  (target T=100000)
  localparam int LAYER_80_P_PIX  = 1;
  localparam int LAYER_80_P_COUT = 80;
  localparam int LAYER_80_P_CIN  = 4;
  localparam int LAYER_80_H      = 40;
  localparam int LAYER_80_W      = 40;
  localparam int LAYER_80_K      = 1;
  localparam int LAYER_80_CIN    = 128;
  localparam int LAYER_80_COUT   = 80;
  localparam int LAYER_80_STRIDE = 1;
  localparam int LAYER_80_PAD    = 0;
  localparam int LAYER_80_GROUP  = 1;
  localparam int LAYER_80_CYCLES = 51200;

  // L81: /model.22/cv1/conv/Conv_quant
  //   shape  Cin=384 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_81_P_PIX  = 1;
  localparam int LAYER_81_P_COUT = 256;
  localparam int LAYER_81_P_CIN  = 2;
  localparam int LAYER_81_H      = 20;
  localparam int LAYER_81_W      = 20;
  localparam int LAYER_81_K      = 1;
  localparam int LAYER_81_CIN    = 384;
  localparam int LAYER_81_COUT   = 256;
  localparam int LAYER_81_STRIDE = 1;
  localparam int LAYER_81_PAD    = 0;
  localparam int LAYER_81_GROUP  = 1;
  localparam int LAYER_81_CYCLES = 76800;

  // L82: /model.23/one2one_cv2.1/one2one_cv2.1.2/Conv_quant
  //   shape  Cin=16 Cout=4 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=102400  cycles=51200  (target T=100000)
  localparam int LAYER_82_P_PIX  = 1;
  localparam int LAYER_82_P_COUT = 2;
  localparam int LAYER_82_P_CIN  = 1;
  localparam int LAYER_82_H      = 40;
  localparam int LAYER_82_W      = 40;
  localparam int LAYER_82_K      = 1;
  localparam int LAYER_82_CIN    = 16;
  localparam int LAYER_82_COUT   = 4;
  localparam int LAYER_82_STRIDE = 1;
  localparam int LAYER_82_PAD    = 0;
  localparam int LAYER_82_GROUP  = 1;
  localparam int LAYER_82_CYCLES = 51200;

  // L83: /model.23/one2one_cv3.1/one2one_cv3.1.1/one2one_cv3.1.1.0/conv/Conv_quant
  //   shape  Cin=80 Cout=80 K=3 stride=1 pad=1 group=80
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=92160000  cycles=64000  (target T=100000)
  localparam int LAYER_83_P_PIX  = 1;
  localparam int LAYER_83_P_COUT = 80;
  localparam int LAYER_83_P_CIN  = 2;
  localparam int LAYER_83_H      = 40;
  localparam int LAYER_83_W      = 40;
  localparam int LAYER_83_K      = 3;
  localparam int LAYER_83_CIN    = 80;
  localparam int LAYER_83_COUT   = 80;
  localparam int LAYER_83_STRIDE = 1;
  localparam int LAYER_83_PAD    = 1;
  localparam int LAYER_83_GROUP  = 80;
  localparam int LAYER_83_CYCLES = 64000;

  // L84: /model.22/m.0/m.0.0/cv1/conv/Conv_quant
  //   shape  Cin=128 Cout=64 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=29491200  cycles=51200  (target T=100000)
  localparam int LAYER_84_P_PIX  = 1;
  localparam int LAYER_84_P_COUT = 64;
  localparam int LAYER_84_P_CIN  = 1;
  localparam int LAYER_84_H      = 20;
  localparam int LAYER_84_W      = 20;
  localparam int LAYER_84_K      = 3;
  localparam int LAYER_84_CIN    = 128;
  localparam int LAYER_84_COUT   = 64;
  localparam int LAYER_84_STRIDE = 1;
  localparam int LAYER_84_PAD    = 1;
  localparam int LAYER_84_GROUP  = 1;
  localparam int LAYER_84_CYCLES = 51200;

  // L85: /model.23/one2one_cv3.1/one2one_cv3.1.1/one2one_cv3.1.1.1/conv/Conv_quant
  //   shape  Cin=80 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=10240000  cycles=64000  (target T=100000)
  localparam int LAYER_85_P_PIX  = 1;
  localparam int LAYER_85_P_COUT = 80;
  localparam int LAYER_85_P_CIN  = 2;
  localparam int LAYER_85_H      = 40;
  localparam int LAYER_85_W      = 40;
  localparam int LAYER_85_K      = 1;
  localparam int LAYER_85_CIN    = 80;
  localparam int LAYER_85_COUT   = 80;
  localparam int LAYER_85_STRIDE = 1;
  localparam int LAYER_85_PAD    = 0;
  localparam int LAYER_85_GROUP  = 1;
  localparam int LAYER_85_CYCLES = 64000;

  // L86: /model.22/m.0/m.0.0/cv2/conv/Conv_quant
  //   shape  Cin=64 Cout=128 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=29491200  cycles=51200  (target T=100000)
  localparam int LAYER_86_P_PIX  = 1;
  localparam int LAYER_86_P_COUT = 64;
  localparam int LAYER_86_P_CIN  = 1;
  localparam int LAYER_86_H      = 20;
  localparam int LAYER_86_W      = 20;
  localparam int LAYER_86_K      = 3;
  localparam int LAYER_86_CIN    = 64;
  localparam int LAYER_86_COUT   = 128;
  localparam int LAYER_86_STRIDE = 1;
  localparam int LAYER_86_PAD    = 1;
  localparam int LAYER_86_GROUP  = 1;
  localparam int LAYER_86_CYCLES = 51200;

  // L87: /model.23/one2one_cv3.1/one2one_cv3.1.2/Conv_quant
  //   shape  Cin=80 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=40 W_in=40 H_out=40 W_out=40
  //   M=10240000  cycles=64000  (target T=100000)
  localparam int LAYER_87_P_PIX  = 1;
  localparam int LAYER_87_P_COUT = 80;
  localparam int LAYER_87_P_CIN  = 2;
  localparam int LAYER_87_H      = 40;
  localparam int LAYER_87_W      = 40;
  localparam int LAYER_87_K      = 1;
  localparam int LAYER_87_CIN    = 80;
  localparam int LAYER_87_COUT   = 80;
  localparam int LAYER_87_STRIDE = 1;
  localparam int LAYER_87_PAD    = 0;
  localparam int LAYER_87_GROUP  = 1;
  localparam int LAYER_87_CYCLES = 64000;

  // L88: /model.22/m.0/m.0.1/attn/qkv/conv/Conv_quant
  //   shape  Cin=128 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=13107200  cycles=51200  (target T=100000)
  localparam int LAYER_88_P_PIX  = 1;
  localparam int LAYER_88_P_COUT = 256;
  localparam int LAYER_88_P_CIN  = 1;
  localparam int LAYER_88_H      = 20;
  localparam int LAYER_88_W      = 20;
  localparam int LAYER_88_K      = 1;
  localparam int LAYER_88_CIN    = 128;
  localparam int LAYER_88_COUT   = 256;
  localparam int LAYER_88_STRIDE = 1;
  localparam int LAYER_88_PAD    = 0;
  localparam int LAYER_88_GROUP  = 1;
  localparam int LAYER_88_CYCLES = 51200;

  // L89: /model.22/m.0/m.0.1/attn/pe/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=3 stride=1 pad=1 group=128
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=58982400  cycles=51200  (target T=100000)
  localparam int LAYER_89_P_PIX  = 1;
  localparam int LAYER_89_P_COUT = 128;
  localparam int LAYER_89_P_CIN  = 1;
  localparam int LAYER_89_H      = 20;
  localparam int LAYER_89_W      = 20;
  localparam int LAYER_89_K      = 3;
  localparam int LAYER_89_CIN    = 128;
  localparam int LAYER_89_COUT   = 128;
  localparam int LAYER_89_STRIDE = 1;
  localparam int LAYER_89_PAD    = 1;
  localparam int LAYER_89_GROUP  = 128;
  localparam int LAYER_89_CYCLES = 51200;

  // L90: /model.22/m.0/m.0.1/attn/proj/conv/Conv_quant
  //   shape  Cin=128 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=6553600  cycles=51200  (target T=100000)
  localparam int LAYER_90_P_PIX  = 1;
  localparam int LAYER_90_P_COUT = 128;
  localparam int LAYER_90_P_CIN  = 1;
  localparam int LAYER_90_H      = 20;
  localparam int LAYER_90_W      = 20;
  localparam int LAYER_90_K      = 1;
  localparam int LAYER_90_CIN    = 128;
  localparam int LAYER_90_COUT   = 128;
  localparam int LAYER_90_STRIDE = 1;
  localparam int LAYER_90_PAD    = 0;
  localparam int LAYER_90_GROUP  = 1;
  localparam int LAYER_90_CYCLES = 51200;

  // L91: /model.22/m.0/m.0.1/ffn/ffn.0/conv/Conv_quant
  //   shape  Cin=128 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=13107200  cycles=51200  (target T=100000)
  localparam int LAYER_91_P_PIX  = 1;
  localparam int LAYER_91_P_COUT = 256;
  localparam int LAYER_91_P_CIN  = 1;
  localparam int LAYER_91_H      = 20;
  localparam int LAYER_91_W      = 20;
  localparam int LAYER_91_K      = 1;
  localparam int LAYER_91_CIN    = 128;
  localparam int LAYER_91_COUT   = 256;
  localparam int LAYER_91_STRIDE = 1;
  localparam int LAYER_91_PAD    = 0;
  localparam int LAYER_91_GROUP  = 1;
  localparam int LAYER_91_CYCLES = 51200;

  // L92: /model.22/m.0/m.0.1/ffn/ffn.1/conv/Conv_quant
  //   shape  Cin=256 Cout=128 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=13107200  cycles=51200  (target T=100000)
  localparam int LAYER_92_P_PIX  = 1;
  localparam int LAYER_92_P_COUT = 128;
  localparam int LAYER_92_P_CIN  = 2;
  localparam int LAYER_92_H      = 20;
  localparam int LAYER_92_W      = 20;
  localparam int LAYER_92_K      = 1;
  localparam int LAYER_92_CIN    = 256;
  localparam int LAYER_92_COUT   = 128;
  localparam int LAYER_92_STRIDE = 1;
  localparam int LAYER_92_PAD    = 0;
  localparam int LAYER_92_GROUP  = 1;
  localparam int LAYER_92_CYCLES = 51200;

  // L93: /model.22/cv2/conv/Conv_quant
  //   shape  Cin=384 Cout=256 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=39321600  cycles=76800  (target T=100000)
  localparam int LAYER_93_P_PIX  = 1;
  localparam int LAYER_93_P_COUT = 256;
  localparam int LAYER_93_P_CIN  = 2;
  localparam int LAYER_93_H      = 20;
  localparam int LAYER_93_W      = 20;
  localparam int LAYER_93_K      = 1;
  localparam int LAYER_93_CIN    = 384;
  localparam int LAYER_93_COUT   = 256;
  localparam int LAYER_93_STRIDE = 1;
  localparam int LAYER_93_PAD    = 0;
  localparam int LAYER_93_GROUP  = 1;
  localparam int LAYER_93_CYCLES = 76800;

  // L94: /model.23/one2one_cv2.2/one2one_cv2.2.0/conv/Conv_quant
  //   shape  Cin=256 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=14745600  cycles=51200  (target T=100000)
  localparam int LAYER_94_P_PIX  = 1;
  localparam int LAYER_94_P_COUT = 16;
  localparam int LAYER_94_P_CIN  = 2;
  localparam int LAYER_94_H      = 20;
  localparam int LAYER_94_W      = 20;
  localparam int LAYER_94_K      = 3;
  localparam int LAYER_94_CIN    = 256;
  localparam int LAYER_94_COUT   = 16;
  localparam int LAYER_94_STRIDE = 1;
  localparam int LAYER_94_PAD    = 1;
  localparam int LAYER_94_GROUP  = 1;
  localparam int LAYER_94_CYCLES = 51200;

  // L95: /model.23/one2one_cv3.2/one2one_cv3.2.0/one2one_cv3.2.0.0/conv/Conv_quant
  //   shape  Cin=256 Cout=256 K=3 stride=1 pad=1 group=256
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=235929600  cycles=51200  (target T=100000)
  localparam int LAYER_95_P_PIX  = 1;
  localparam int LAYER_95_P_COUT = 256;
  localparam int LAYER_95_P_CIN  = 2;
  localparam int LAYER_95_H      = 20;
  localparam int LAYER_95_W      = 20;
  localparam int LAYER_95_K      = 3;
  localparam int LAYER_95_CIN    = 256;
  localparam int LAYER_95_COUT   = 256;
  localparam int LAYER_95_STRIDE = 1;
  localparam int LAYER_95_PAD    = 1;
  localparam int LAYER_95_GROUP  = 256;
  localparam int LAYER_95_CYCLES = 51200;

  // L96: /model.23/one2one_cv2.2/one2one_cv2.2.1/conv/Conv_quant
  //   shape  Cin=16 Cout=16 K=3 stride=1 pad=1 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=921600  cycles=51200  (target T=100000)
  localparam int LAYER_96_P_PIX  = 1;
  localparam int LAYER_96_P_COUT = 2;
  localparam int LAYER_96_P_CIN  = 1;
  localparam int LAYER_96_H      = 20;
  localparam int LAYER_96_W      = 20;
  localparam int LAYER_96_K      = 3;
  localparam int LAYER_96_CIN    = 16;
  localparam int LAYER_96_COUT   = 16;
  localparam int LAYER_96_STRIDE = 1;
  localparam int LAYER_96_PAD    = 1;
  localparam int LAYER_96_GROUP  = 1;
  localparam int LAYER_96_CYCLES = 51200;

  // L97: /model.23/one2one_cv3.2/one2one_cv3.2.0/one2one_cv3.2.0.1/conv/Conv_quant
  //   shape  Cin=256 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=8192000  cycles=51200  (target T=100000)
  localparam int LAYER_97_P_PIX  = 1;
  localparam int LAYER_97_P_COUT = 80;
  localparam int LAYER_97_P_CIN  = 2;
  localparam int LAYER_97_H      = 20;
  localparam int LAYER_97_W      = 20;
  localparam int LAYER_97_K      = 1;
  localparam int LAYER_97_CIN    = 256;
  localparam int LAYER_97_COUT   = 80;
  localparam int LAYER_97_STRIDE = 1;
  localparam int LAYER_97_PAD    = 0;
  localparam int LAYER_97_GROUP  = 1;
  localparam int LAYER_97_CYCLES = 51200;

  // L98: /model.23/one2one_cv2.2/one2one_cv2.2.2/Conv_quant
  //   shape  Cin=16 Cout=4 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=25600  cycles=25600  (target T=100000)
  localparam int LAYER_98_P_PIX  = 1;
  localparam int LAYER_98_P_COUT = 1;
  localparam int LAYER_98_P_CIN  = 1;
  localparam int LAYER_98_H      = 20;
  localparam int LAYER_98_W      = 20;
  localparam int LAYER_98_K      = 1;
  localparam int LAYER_98_CIN    = 16;
  localparam int LAYER_98_COUT   = 4;
  localparam int LAYER_98_STRIDE = 1;
  localparam int LAYER_98_PAD    = 0;
  localparam int LAYER_98_GROUP  = 1;
  localparam int LAYER_98_CYCLES = 25600;

  // L99: /model.23/one2one_cv3.2/one2one_cv3.2.1/one2one_cv3.2.1.0/conv/Conv_quant
  //   shape  Cin=80 Cout=80 K=3 stride=1 pad=1 group=80
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=23040000  cycles=64000  (target T=100000)
  localparam int LAYER_99_P_PIX  = 1;
  localparam int LAYER_99_P_COUT = 40;
  localparam int LAYER_99_P_CIN  = 1;
  localparam int LAYER_99_H      = 20;
  localparam int LAYER_99_W      = 20;
  localparam int LAYER_99_K      = 3;
  localparam int LAYER_99_CIN    = 80;
  localparam int LAYER_99_COUT   = 80;
  localparam int LAYER_99_STRIDE = 1;
  localparam int LAYER_99_PAD    = 1;
  localparam int LAYER_99_GROUP  = 80;
  localparam int LAYER_99_CYCLES = 64000;

  // L100: /model.23/one2one_cv3.2/one2one_cv3.2.1/one2one_cv3.2.1.1/conv/Conv_quant
  //   shape  Cin=80 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=2560000  cycles=64000  (target T=100000)
  localparam int LAYER_100_P_PIX  = 1;
  localparam int LAYER_100_P_COUT = 40;
  localparam int LAYER_100_P_CIN  = 1;
  localparam int LAYER_100_H      = 20;
  localparam int LAYER_100_W      = 20;
  localparam int LAYER_100_K      = 1;
  localparam int LAYER_100_CIN    = 80;
  localparam int LAYER_100_COUT   = 80;
  localparam int LAYER_100_STRIDE = 1;
  localparam int LAYER_100_PAD    = 0;
  localparam int LAYER_100_GROUP  = 1;
  localparam int LAYER_100_CYCLES = 64000;

  // L101: /model.23/one2one_cv3.2/one2one_cv3.2.2/Conv_quant
  //   shape  Cin=80 Cout=80 K=1 stride=1 pad=0 group=1
  //   H_in=20 W_in=20 H_out=20 W_out=20
  //   M=2560000  cycles=64000  (target T=100000)
  localparam int LAYER_101_P_PIX  = 1;
  localparam int LAYER_101_P_COUT = 40;
  localparam int LAYER_101_P_CIN  = 1;
  localparam int LAYER_101_H      = 20;
  localparam int LAYER_101_W      = 20;
  localparam int LAYER_101_K      = 1;
  localparam int LAYER_101_CIN    = 80;
  localparam int LAYER_101_COUT   = 80;
  localparam int LAYER_101_STRIDE = 1;
  localparam int LAYER_101_PAD    = 0;
  localparam int LAYER_101_GROUP  = 1;
  localparam int LAYER_101_CYCLES = 64000;

endpackage
// verilator lint_on UNUSEDPARAM
