#!/usr/bin/env python3
# Copyright (c) 2026 vibeyolo
# SPDX-License-Identifier: Apache-2.0
#
# chip_area.py — whole-chip area on a chosen PDK and YOLO variant.
#
# Ties the three terms together for ONE command:
#   * logic  : MAC datapath = (Σ per-layer MAC units) × area(mac8) × overhead.
#              area(mac8) is RE-SYNTHESIZED against the PDK's stdcell .lib if one
#              is configured (so a new node = just a new liberty path); otherwise
#              it falls back to gate-count × gate_um2.
#   * ROM    : weight storage = Σ K²·Cin·Cout·8 bits × rom_um2_per_bit.
#   * SRAM   : inter-stage activation path, tiled by tools/sram_bw.py.
#
# Everything is driven by a balanced scale report + a PDK profile, so:
#   PDK=sky130 python3 tools/chip_area.py                 # this open node
#   python3 tools/chip_area.py --pdk sky130 --scale-report <variant>.md
#   (drop a TSMC profile into sram_model.PDKS with its .lib + macro -> same flow)

import os, re, sys, subprocess, argparse
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sram_model as sm
import sram_bw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAC8 = os.path.join(ROOT, "hw/ip/mac8/rtl/mac8.sv")
OVERHEAD = 1.6                  # adders + fp16 requant + ctl/glue (cf. area_estimate.py)
LOGIC_UTIL = 0.65               # P&R utilization: synth cell area -> physical die
                                # area (routing, clock tree, whitespace). Puts
                                # logic on the same physical basis as the SRAM/ROM
                                # macro areas. Real number comes from P&R.
RETICLE_MM2 = 858.0             # full reticle field ~26×33 mm (max single die)
HALF_RETICLE_MM2 = 430.0


def mac8_um2(pdk):
    """Area of one mac8 on this PDK: cached value, else synth against liberty."""
    if pdk.mac8_um2 > 0:
        return pdk.mac8_um2
    if pdk.liberty and os.path.exists(pdk.liberty):
        script = (f"read_verilog -sv {MAC8}; synth -top mac8 -flatten; "
                  f"dfflibmap -liberty {pdk.liberty}; abc -liberty {pdk.liberty}; "
                  f"opt_clean -purge; stat -liberty {pdk.liberty}")
        out = subprocess.run(["yosys", "-p", script],
                             capture_output=True, text=True).stdout
        m = re.findall(r"Chip area for module.*?:\s*([\d.]+)", out)
        if m:
            return float(m[-1])
    return None                  # caller handles gate-count fallback


def mac8_gates():
    """Generic-cell count for mac8 (PDK-less fallback, cf. area_estimate.py)."""
    out = subprocess.run(["yosys", "-q", "-p",
        f"read_verilog -sv {MAC8}; synth -top mac8 -flatten; "
        "abc -g AND,NAND,OR,NOR,XOR,XNOR,ANDNOT,ORNOT,MUX; stat"],
        capture_output=True, text=True).stdout
    c = [int(x) for x in re.findall(r"(\d+)\s+cells", out)]
    return c[-1] if c else 634


def main():
    ap = argparse.ArgumentParser(description="whole-chip area on a PDK")
    ap.add_argument("--pdk", default=os.environ.get("PDK", "n16"),
                    choices=list(sm.PDKS))
    ap.add_argument("--scale-report", default=sram_bw.BAL)
    args = ap.parse_args()
    pdk = sm.set_pdk(args.pdk); sm._sync()

    rows = sram_bw.parse_balanced(args.scale_report)

    # ── logic: MAC instances + per-mac8 area ─────────────────────────────
    tot_mac = sum(r["ppix"] * r["pcout"] * (r["k"]**2 * r["pcin"]) for r in rows)
    a8 = mac8_um2(pdk)
    if a8 is None:                          # no liberty -> gate-count basis
        a8 = mac8_gates() * pdk.gate_um2
        mac_basis = f"{mac8_gates()} gates × {pdk.gate_um2} µm² synth"
    else:
        mac_basis = f"{a8:,.0f} µm²/mac8 synth"
    # synth cell area -> physical die area (P&R util), matching macro areas.
    logic_um2 = tot_mac * a8 * OVERHEAD / LOGIC_UTIL
    mac_basis += f" ÷{LOGIC_UTIL} P&R"

    # ── ROM: dense weight storage (chip stores depthwise zero-expanded) ──
    rom_bits = sum(r["k"]**2 * r["cin"] * r["cout"] * 8 for r in rows)
    rom_um2  = rom_bits * pdk.rom_um2_per_bit

    # ── SRAM: inter-stage activation path (reuse sram_bw enumeration) ────
    tiles = [sram_bw.tile(m) for m in sram_bw.enumerate_mems(rows)]
    sram_um2 = sum(t.area_um2 for t in tiles)

    tot_um2 = logic_um2 + rom_um2 + sram_um2
    mm2 = lambda u: u / 1e6
    total = mm2(tot_um2)

    def row(name, um2, extra=""):
        return (f"| {name} | {mm2(um2):,.2f} | {mm2(um2)/total*100:4.1f}% "
                f"| {extra} |")

    L = []
    P = L.append
    P(f"# Chip area — PDK `{pdk.name}` · {len(rows)} conv layers\n")
    P(f"_Generated by `tools/chip_area.py`. Logic re-synthesized against the "
      f"PDK liberty where available; SRAM/ROM from measured macro density. "
      f"Clock {pdk.clk_hz/1e9:g} GHz._\n")
    P("| block | area (mm²) | share | basis |")
    P("|-------|----------:|------:|-------|")
    P(row("Logic (MAC datapath ×1.6)", logic_um2, f"{tot_mac:,} MACs · {mac_basis}"))
    P(row("Weight ROM", rom_um2, f"{rom_bits/8/1e6:.2f} MB · {pdk.rom_um2_per_bit:g} µm²/bit"))
    P(row("Activation SRAM", sram_um2, f"{sum(t.cap_bits for t in tiles)/8/1e6:.2f} MB · {len(tiles)} mems"))
    P(f"| **Total** | **{total:,.2f}** | 100% | |")
    P("")
    P("| reference | value |")
    P("|-----------|------:|")
    P(f"| total die area | **{total:,.1f} mm²** |")
    P(f"| vs half-reticle ({HALF_RETICLE_MM2:.0f} mm²) | {total/HALF_RETICLE_MM2:.2f}× |")
    P(f"| vs full reticle ({RETICLE_MM2:.0f} mm²) | {total/RETICLE_MM2:.2f}× "
      f"{'— ⚠️ exceeds one reticle (not a single die)' if total>RETICLE_MM2 else ''} |")
    P(f"| chip clock | {pdk.clk_hz/1e9:g} GHz |")
    P(f"| throughput (II=82,951) | {pdk.clk_hz/82_951:,.0f} FPS |")
    P("")

    out = os.path.join(ROOT, "reports", f"CHIP_AREA_{pdk.name}.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("\n".join(L) + "\n")

    print(f"[pdk={pdk.name}] logic {mm2(logic_um2):,.1f} + rom {mm2(rom_um2):,.1f} "
          f"+ sram {mm2(sram_um2):,.1f} = {total:,.1f} mm²  "
          f"({total/HALF_RETICLE_MM2:.2f}× half-reticle, "
          f"{pdk.clk_hz/82_951:,.0f} FPS @ {pdk.clk_hz/1e9:g}GHz)")
    print(f"wrote {os.path.relpath(out, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
