#!/usr/bin/env python3
# Copyright (c) 2026 vibeyolo
# SPDX-License-Identifier: Apache-2.0
#
# gen_core.py — emit the structural yolo26n_core dataflow netlist.
#
# Non-destructive: writes integ/generated/core/{yolo26n_layers_pkg.sv,
# yolo26n_core_impl.sv}. The hand-frozen hw/ip/yolo26n_top/ boundary is not
# touched; yolo26n_core_impl is the body PD floorplans behind that boundary.
#
# Topology (conv activation edges + glue nodes) is read straight from the ONNX
# (source of truth, footgun #8). Channel widths for every glue tensor come from
# ONNX shape-inference so concat/slice/residual widths are exact (lint-correct
# without hand-tracing the nested C2fCIB blocks). Conv dims come from the
# DV-capped scale_pkg so the netlist elaborates for partitioned lint (footgun
# #4: whole-chip sim is infeasible; lint proves the structural composition).
#
# Emission:
#   * 102 conv_stage instances (generate array) reading a per-layer input bus.
#   * C2f / neck glue as channel-parallel structural ops over those buses:
#       - Slice / Split  -> channel subrange   (zero-area bus select)
#       - Concat         -> bus concatenation  (zero-area)
#       - residual Add   -> per-channel add_rq bank (real requant gates)
#   * the six DV'd integration blocks (sppf, 2x upsample_concat, 2x attn,
#     detect_head) instantiated at their graph positions, fed by member convs.
#   * 4 skip-FIFO banks (skip_buf) at the verified taps m.4/m.6/m.10/m.13 cv2.
#
# This is connectivity / PD-floorplan RTL: per-region handshake timing is
# inherited from the already-DV'd blocks; the netlist's job is structural
# composition + width correctness, validated by partitioned lint.

import os, re, onnx
import onnx.shape_inference as si

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ONNX = os.path.join(ROOT, "integ/yolo26n/model_int8.onnx")
DVPKG = os.path.join(ROOT, "integ/scale/scale_pkg_dv.sv")
BAL  = os.path.join(ROOT, "integ/generated/scale/scale_report_balanced.md")
OUTD = os.path.join(ROOT, "integ/generated/core")

# ── conv idx -> node name (balanced report order = canonical layer index) ──
idx2name = {}
for line in open(BAL):
    mm = re.match(r"\|\s*(\d+)\s*\|\s*(/model[^|]+?)\s*\|", line)
    if mm:
        idx2name[int(mm.group(1))] = mm.group(2).strip()
NL = len(idx2name)
assert NL == 102, NL
name2idx = {v: k for k, v in idx2name.items()}

# ── conv dims from DV-capped scale_pkg ──
dv = open(DVPKG).read()
def P(i, f):
    m = re.search(rf"LAYER_{i}_{f}\s*=\s*(\d+)", dv)
    return int(m.group(1)) if m else 0
DIMS = {}
for i in range(NL):
    st = P(i, "STRIDE") or 1
    DIMS[i] = dict(CIN=P(i,"CIN"), COUT=P(i,"COUT"), K=P(i,"K"), STRIDE=st,
                   PAD=P(i,"PAD"), H_OUT=P(i,"H"), W_OUT=P(i,"W"),
                   P_COUT=P(i,"P_COUT"), P_CIN=P(i,"P_CIN"))
def COUT(i): return DIMS[i]["COUT"]
def CIN(i):  return DIMS[i]["CIN"]

# ── ONNX graph + per-tensor channel count ──
m = si.infer_shapes(onnx.load(ONNX))
g = m.graph
prod = {}
for n in g.node:
    for o in n.output: prod[o] = n
shp = {}
for vi in list(g.value_info) + list(g.input) + list(g.output):
    shp[vi.name] = [x.dim_value for x in vi.type.tensor_type.shape.dim]
def chan(t):
    d = shp.get(t, [])
    return d[1] if len(d) >= 2 else 0

def to_conv(t, d=0):
    """Resolve a tensor down its requant chain to the producing conv idx."""
    if d > 90: return None
    n = prod.get(t)
    if n is None: return None
    if n.op_type == "ConvInteger":
        return name2idx.get(n.name)
    return to_conv(n.input[0], d + 1)

MAXC = 512  # widest activation (model.9 concat = 512)

# ── Block cluster definitions ─────────────────────────────────────────────
# Each block collapses a glue cluster; its OUTPUT tensor short-circuits
# resolve_net so the subsumed internal nodes (Resize/MaxPool/Split/attn Adds)
# are never descended into. Member convs feeding the block are normal stages.
#
# attn spl1 = the residual-identity branch into the transformer block.
SKIP_TAPS = {10, 20, 39, 48}   # m.4/cv2, m.6/cv2, m.10/cv2, m.13/cv2

# block instances filled while emitting; (name, out_tensor) -> wirename
BLOCK_OUT = {
    "/model.9/Concat_output_0":            "g_sppf",
    "/model.12/Concat_output_0":           "g_ups11",
    "/model.15/Concat_output_0":           "g_ups14",
    # attn block now emits ATTN_OUT (= attention(qkv) + pe) at the attn/Add node.
    # The proj conv consumes it; the two PSA residual adds (proj+spl1, +ffn1)
    # are NOT blocked here so resolve_net builds them as real add_rq banks.
    "/model.10/m/m.0/attn/Add_output_0":     "g_attn10",
    "/model.22/m.0/m.0.1/attn/Add_output_0": "g_attn22",
}

# ── Emit layers package ────────────────────────────────────────────────────
os.makedirs(OUTD, exist_ok=True)
pk = []
pk.append("// GENERATED by tools/gen_core.py — do not edit.")
pk.append("// Per-layer dims for the 102 conv stages (DV-capped parallelism).")
pk.append("package yolo26n_layers_pkg;")
pk.append(f"  localparam int NL = {NL};")
pk.append(f"  localparam int MAXC = {MAXC};")
for f in ["CIN","COUT","K","STRIDE","PAD","HIN","WIN","PCOUT","PCIN"]:
    vals = []
    for i in range(NL):
        d = DIMS[i]
        v = {"CIN":d["CIN"],"COUT":d["COUT"],"K":d["K"],"STRIDE":d["STRIDE"],
             "PAD":d["PAD"],"HIN":d["H_OUT"]*d["STRIDE"],"WIN":d["W_OUT"]*d["STRIDE"],
             "PCOUT":d["P_COUT"],"PCIN":d["P_CIN"]}[f]
        vals.append(str(v))
    pk.append(f"  localparam int L_{f} [NL] = '{{{', '.join(vals)}}};")
src_idx = []
for i in range(NL):
    node = next(nn for nn in g.node if nn.name == idx2name[i])
    src_idx.append(to_conv(node.input[0]) if to_conv(node.input[0]) is not None else -1)
pk.append(f"  localparam int L_SRC [NL] = '{{{', '.join(str(x) for x in src_idx)}}};")
pk.append("endpackage")
open(os.path.join(OUTD, "yolo26n_layers_pkg.sv"), "w").write("\n".join(pk) + "\n")

# ── Structural net resolver ────────────────────────────────────────────────
# resolve_net(tensor) -> dict(base=<sv identifier>, lo=<low channel>, w=<width>,
#                             v=<valid expr>). Slicing is base[lo+w-1:lo].
decls, glue, insts = [], [], []
memo = {}
uid = [0]
def newname(p):
    uid[0] += 1
    return f"{p}{uid[0]}"

FP1 = "16'h3C00"  # 1.0 in fp16  (connectivity-level requant scale placeholder)
FP0 = "16'h0000"

def expr(d):
    return f"{d['base']}[{d['lo']+d['w']-1}:{d['lo']}]"

def materialize(d, w):
    """Force dict d into a freshly declared flat base wire of width w."""
    nm = newname("g_net")
    decls.append(f"  logic signed [{w-1}:0][7:0] {nm};")
    decls.append(f"  logic                       {nm}_v;")
    glue.append(f"  assign {nm}   = {expr(d)};")
    glue.append(f"  assign {nm}_v = {d['v']};")
    return dict(base=nm, lo=0, w=w, v=f"{nm}_v")

def conv_net(idx):
    """Output bus of conv idx — through a skip_buf bank if it is a skip tap."""
    if idx in SKIP_TAPS:
        nm = f"g_skip{idx}"
        if nm not in memo:
            c, st = COUT(idx), DIMS[idx]
            ho, wo = st["H_OUT"], st["W_OUT"]
            decls.append(f"  // skip-FIFO bank: tap conv#{idx} ({idx2name[idx]}) {ho}x{wo}x{c}")
            decls.append(f"  logic signed [{c-1}:0][7:0] {nm};")
            decls.append(f"  logic                       {nm}_v;")
            insts.append(f"  for (genvar sb = 0; sb < {c}; sb++) begin : g_{nm}")
            insts.append(f"    skip_buf #(.H({ho}), .W({wo}), .C(1)) u_{nm} (")
            insts.append(f"      .clk_i(clk_i), .rst_ni(rst_ni), .clr_i(start_i),")
            insts.append(f"      .wvalid_i(act_valid[{idx}]), .wready_o(), .wdata_i(act[{idx}][sb]),")
            insts.append(f"      .rvalid_o(), .rready_i(1'b1), .rdata_o({nm}[sb]),")
            insts.append(f"      .full_o(), .empty_o());")
            insts.append(f"    end")
            glue.append(f"  assign {nm}_v = act_valid[{idx}];")
            memo[nm] = dict(base=nm, lo=0, w=c, v=f"{nm}_v")
        return memo[nm]
    return dict(base=f"act[{idx}]", lo=0, w=COUT(idx), v=f"act_valid[{idx}]")

# pe (depthwise-on-V) convs sit *inside* the attention region: their input is
# the attn-internal Split of qkv, on a reshaped [B,heads,..] tensor where ONNX
# dim-1 is not the channel axis. Feed them a width-correct V stand-in (low C_FE
# of the qkv conv) — connectivity-level, like the rest of the attn region.
IN_OVERRIDE = {
    35: dict(e="act[34][127:0]", v="act_valid[34]"),
    89: dict(e="act[88][127:0]", v="act_valid[88]"),
}

def resolve_net(t, depth=0):
    if t in BLOCK_OUT:
        nm = BLOCK_OUT[t]
        return dict(base=nm, lo=0, w=chan(t), v=f"{nm}_v")
    if t in memo:
        return memo[t]
    n = prod.get(t)
    if n is None:
        return dict(base="g_img", lo=0, w=3, v="g_img_v")   # network input
    op = n.op_type
    if op == "ConvInteger":
        return conv_net(name2idx.get(n.name))
    if op == "Concat":
        kids = [resolve_net(i, depth+1) for i in n.input if i in prod or i == "" or prod.get(i)]
        kids = [k for k in kids if k]
        w = chan(t)
        # channel 0 = first onnx input  ->  first input is the low (rightmost) slice
        cat = "{" + ", ".join(expr(k) for k in reversed(kids)) + "}"
        nm = newname("g_cat")
        decls.append(f"  logic signed [{w-1}:0][7:0] {nm};")
        decls.append(f"  logic                       {nm}_v;")
        glue.append(f"  assign {nm}   = {cat};")
        glue.append(f"  assign {nm}_v = {kids[-1]['v']};")
        memo[t] = dict(base=nm, lo=0, w=w, v=f"{nm}_v")
        return memo[t]
    if op == "Slice":
        par = resolve_net(n.input[0], depth+1)
        w = chan(t)
        # C2f always splits a 2c bus into two equal halves; the first Slice of a
        # given parent takes the low half, the second the high half.
        sibs = [nn for nn in g.node if nn.op_type == "Slice" and nn.input[0] == n.input[0]]
        order = [nn.name for nn in sibs].index(n.name)
        off = order * w
        memo[t] = dict(base=par["base"], lo=par["lo"]+off, w=w, v=par["v"])
        return memo[t]
    if op == "Split":
        par = resolve_net(n.input[0], depth+1)
        w = chan(t)
        oi = list(n.output).index(t)
        memo[t] = dict(base=par["base"], lo=par["lo"]+oi*w, w=w, v=par["v"])
        return memo[t]
    if op == "Add":
        nm = n.name.lower()
        if "bias_add" in nm or "quant" in nm:        # requant bias -> conv chain
            return resolve_net(n.input[0], depth+1)
        # residual Add: per-channel add_rq bank (real requant gates)
        a = resolve_net(n.input[0], depth+1)
        b = resolve_net(n.input[1], depth+1)
        w = chan(t)
        rn = newname("g_add")
        decls.append(f"  logic signed [{w-1}:0][7:0] {rn};")
        decls.append(f"  logic                       {rn}_v;")
        am, bm = expr(a), expr(b)
        insts.append(f"  for (genvar ar = 0; ar < {w}; ar++) begin : g_{rn}")
        insts.append(f"    add_rq u_{rn} (.clk_i(clk_i), .rst_ni(rst_ni),")
        insts.append(f"      .valid_i({a['v']}), .a_i8_i({am}[ar]), .b_i8_i({bm}[ar]),")
        insts.append(f"      .scale_a_fp16_i({FP1}), .scale_b_fp16_i({FP1}),")
        insts.append(f"      .inv_out_scale_fp16_i({FP1}), .bias_fp16_i({FP0}),")
        insts.append(f"      .valid_o(), .y_o({rn}[ar]));")
        insts.append(f"    end")
        glue.append(f"  assign {rn}_v = {a['v']};")
        memo[t] = dict(base=rn, lo=0, w=w, v=f"{rn}_v")
        return memo[t]
    if op in ("Resize", "MaxPool"):                  # only reached if un-blocked
        return resolve_net(n.input[0], depth+1)
    # requant / dequant op (Mul, Cast, Clip, Round, bias Add, ...) — keep
    # walking input[0]; we stop at the first ConvInteger, glue node, or block
    # output. (Never short-circuit to_conv here: that would jump *past* an
    # intervening Slice/Concat/residual-Add down to its conv source.)
    return resolve_net(n.input[0], depth+1)

# ── Build the structural body ──────────────────────────────────────────────
c = []
A = c.append
A("// GENERATED by tools/gen_core.py — do not edit.")
A("// Structural yolo26n_core dataflow netlist (PD floorplan / connectivity).")
A("// 102 conv_stage + 6 verified blocks + 4 skip-FIFO banks + frame sequencer.")
A("// Whole-chip Verilator elaboration is infeasible (footgun #4); validated by")
A("// partitioned lint. Conv params are DV-capped so the netlist elaborates.")
A("// Glue widths are exact from ONNX shape-inference; per-region handshake")
A("// timing is inherited from the already-DV'd blocks (connectivity netlist).")
A("")
A("module yolo26n_core_impl")
A("  import yolo26n_layers_pkg::*;")
A("(")
A("  input  logic                 clk_i,")
A("  input  logic                 rst_ni,")
A("  input  logic                 start_i,")
A("  input  logic                 pix_valid_i,")
A("  output logic                 pix_ready_o,")
A("  input  logic signed [2:0][7:0] pix_data_i,")
A("  output logic                 det_valid_o,")
A("  output logic [13:0]          det_anchor_o,")
A("  output logic [3:0][15:0]     det_box_o,")
A("  output logic [79:0][15:0]    det_logits_o,")
A("  output logic                 done_o")
A(");")
A("")
A("  // ── per-conv output bus + valid + frame start/done ──")
A("  logic signed [NL-1:0][MAXC-1:0][7:0] act;")
A("  logic        [NL-1:0]                act_valid;")
A("  logic        [NL-1:0]                stage_done;")
A("  logic        [NL-1:0]                stage_start;")
A("")
A("  // network image input net (3ch int8)")
A("  logic signed [2:0][7:0] g_img;")
A("  logic                   g_img_v;")
A("  assign g_img   = pix_data_i;")
A("  assign g_img_v = pix_valid_i;")
A("")
A("  // per-conv assembled input bus (low CIN channels used)")
A("  logic signed [MAXC-1:0][7:0] cin [NL];")
A("  logic                        cin_v [NL];")
A("")
A("  // frame sequencer: daisy-chain start->done across topological order")
A("  assign stage_start[0] = start_i;")
A("  for (genvar gs = 1; gs < NL; gs++) begin : g_seq")
A("    assign stage_start[gs] = stage_done[gs-1];")
A("  end")
A("")

# Resolve every conv input -> per-layer cin assign (this populates decls/glue/insts)
cin_assigns = []
for i in range(NL):
    ci = CIN(i)
    if i in IN_OVERRIDE:
        ov = IN_OVERRIDE[i]
        cin_assigns.append(f"  assign cin[{i}][{ci-1}:0] = {ov['e']};")
        cin_assigns.append(f"  assign cin_v[{i}]      = {ov['v']};")
        continue
    node = next(nn for nn in g.node if nn.name == idx2name[i])
    d = resolve_net(node.input[0])
    cin_assigns.append(f"  assign cin[{i}][{ci-1}:0] = {expr(d)};")
    cin_assigns.append(f"  assign cin_v[{i}]      = {d['v']};")

# block input feeds (resolve member-conv nets; reuse conv_net for skip routing)
def feed(idx): return conv_net(idx)

# ── emit glue net declarations ──
A("  // ── structural glue nets (slice / concat / residual add / skip) ──")
for line in decls: A(line)
A("")
A("  // ── per-conv input assembly ──")
for line in cin_assigns: A(line)
A("")
A("  // ── glue assigns ──")
for line in glue: A(line)
A("")

# ── 102 conv stages ──
A("  // ── 102 conv stages ──")
A("  for (genvar i = 0; i < NL; i++) begin : g_conv")
A("    localparam int CI=L_CIN[i], CO=L_COUT[i], KK=L_K[i], ST=L_STRIDE[i];")
A("    localparam int PD=L_PAD[i], HI=L_HIN[i], WI=L_WIN[i];")
A("    localparam int PCO=L_PCOUT[i], PCI=L_PCIN[i];")
A("    logic signed [CO-1:0][7:0] yout;")
A("    logic                      yout_valid;")
A("    conv_stage #(")
A("      .CIN(CI), .COUT(CO), .K(KK), .STRIDE(ST), .PAD(PD),")
A("      .H_IN(HI), .W_IN(WI), .P_COUT(PCO), .P_CIN(PCI), .SILU(1)")
A("    ) u_stage (")
A("      .clk_i(clk_i), .rst_ni(rst_ni),")
A("      .start_i(stage_start[i]), .done_o(stage_done[i]),")
A("      .ivalid_i(cin_v[i]), .iready_o(), .idata_i(cin[i][CI-1:0]),")
A("      .ovalid_o(yout_valid), .oready_i(1'b1), .odata_o(yout)")
A("    );")
A("    for (genvar ch = 0; ch < CO;   ch++) begin : g_yo  assign act[i][ch] = yout[ch]; end")
A("    for (genvar ch = CO; ch < MAXC; ch++) begin : g_zp assign act[i][ch] = '0;       end")
A("    assign act_valid[i] = yout_valid;")
A("  end")
A("")

# ── skip / glue instances (add_rq banks, skip_buf banks) ──
A("  // ── glue instances (residual add_rq banks, skip-FIFO banks) ──")
for line in insts: A(line)
A("")

# ── six integration blocks ──
A("  // ── integration block 1/6: SPPF (m.9) ──")
A(f"  logic signed [511:0][7:0] g_sppf; logic g_sppf_v;")
A("  sppf #(.H(20), .W(20), .C(128), .K(5)) u_sppf (")
A("    .clk_i(clk_i), .rst_ni(rst_ni), .start_i(start_i),")
A(f"    .ivalid_i({feed(31)['v']}), .iready_o(), .idata_i({expr(feed(31))}),")
A("    .ovalid_o(g_sppf_v), .oready_i(1'b1), .odata_o(g_sppf), .done_o());")
A("")
A("  // ── integration block 2/6: upsample+concat (m.11/m.12) — P5^ + P4 skip ──")
A(f"  logic signed [383:0][7:0] g_ups11; logic g_ups11_v;")
A("  upsample_concat #(.H_A(20),.W_A(20),.C_A(256),.H_B(40),.W_B(40),.C_B(128)) u_ups11 (")
A("    .clk_i(clk_i), .rst_ni(rst_ni), .start_i(start_i),")
A(f"    .avalid_i({feed(39)['v']}), .aready_o(), .adata_i({expr(feed(39))}),")
A(f"    .bvalid_i({feed(20)['v']}), .bready_o(), .bdata_i({expr(feed(20))}),")
A("    .ovalid_o(g_ups11_v), .oready_i(1'b1), .odata_o(g_ups11), .done_o());")
A("")
A("  // ── integration block 3/6: upsample+concat (m.14/m.15) — P4^ + P3 skip ──")
A(f"  logic signed [255:0][7:0] g_ups14; logic g_ups14_v;")
A("  upsample_concat #(.H_A(40),.W_A(40),.C_A(128),.H_B(80),.W_B(80),.C_B(128)) u_ups14 (")
A("    .clk_i(clk_i), .rst_ni(rst_ni), .start_i(start_i),")
A(f"    .avalid_i({feed(48)['v']}), .aready_o(), .adata_i({expr(feed(48))}),")
A(f"    .bvalid_i({feed(10)['v']}), .bready_o(), .bdata_i({expr(feed(10))}),")
A("    .ovalid_o(g_ups14_v), .oready_i(1'b1), .odata_o(g_ups14), .done_o());")
A("")
A("  // ── integration block 4/6: attention PSA (m.10) — qkv,pe -> ATTN_OUT ──")
A("  // proj conv (#36) reads g_attn10; proj+spl1 and +ffn1 residuals are")
A("  // emitted as add_rq banks by resolve_net (real glue, not absorbed here).")
A(f"  logic signed [127:0][7:0] g_attn10; logic g_attn10_v;")
A("  attn u_attn10 (")
A("    .clk_i(clk_i), .rst_ni(rst_ni), .start_i(start_i),")
A(f"    .qkv_valid_i({feed(34)['v']}),  .qkv_ready_o(),  .qkv_data_i({expr(feed(34))}),")
A(f"    .pe_valid_i({feed(35)['v']}),   .pe_ready_o(),   .pe_data_i({expr(feed(35))}),")
A("    .ovalid_o(g_attn10_v), .oready_i(1'b1), .odata_o(g_attn10), .done_o());")
A("")
A("  // ── integration block 5/6: attention PSA (m.22) — qkv,pe -> ATTN_OUT ──")
A(f"  logic signed [127:0][7:0] g_attn22; logic g_attn22_v;")
A("  attn u_attn22 (")
A("    .clk_i(clk_i), .rst_ni(rst_ni), .start_i(start_i),")
A(f"    .qkv_valid_i({feed(88)['v']}),  .qkv_ready_o(),  .qkv_data_i({expr(feed(88))}),")
A(f"    .pe_valid_i({feed(89)['v']}),   .pe_ready_o(),   .pe_data_i({expr(feed(89))}),")
A("    .ovalid_o(g_attn22_v), .oready_i(1'b1), .odata_o(g_attn22), .done_o());")
A("")
A("  // ── integration block 6/6: detect head (m.23) — decode+topk+gather ──")
A("  logic [15:0] s_box [3]; logic [15:0] s_cls [3];")
A(f"  assign s_box = '{{{FP1}, {FP1}, {FP1}}};")
A(f"  assign s_cls = '{{{FP1}, {FP1}, {FP1}}};")
A("  detect_head #(.N_ANCHOR(8400), .N_CLS(80), .K(300), .IDX_W(14)) u_detect (")
A("    .clk_i(clk_i), .rst_ni(rst_ni), .start_i(start_i),")
A("    .s_box_i(s_box), .s_cls_i(s_cls),")
A("    .in_ready_o(), .in_valid_i(act_valid[64]),")
A("    .box_i(act[64][3:0]), .cls_i(act[70][79:0]),")
A("    .out_valid_o(det_valid_o), .out_anchor_o(det_anchor_o),")
A("    .out_box_o(det_box_o), .out_logits_o(det_logits_o), .done_o(done_o));")
A("")
A("  assign pix_ready_o = 1'b1;")
A("")
A("  // verilator lint_off UNUSEDSIGNAL")
A("  wire _unused = ^{act, g_sppf, g_ups11, g_ups14, g_attn10, g_attn22,")
A("                   g_sppf_v, g_ups11_v, g_ups14_v, g_attn10_v, g_attn22_v,")
A("                   stage_done, cin_v[0]};")
A("  // verilator lint_on UNUSEDSIGNAL")
A("endmodule")
open(os.path.join(OUTD, "yolo26n_core_impl.sv"), "w").write("\n".join(c) + "\n")

# report
nglue_add = sum(1 for l in insts if "add_rq u_" in l)
print(f"emitted {OUTD}/yolo26n_layers_pkg.sv + yolo26n_core_impl.sv")
print(f"  102 conv stages; {len([l for l in insts if 'skip_buf' in l])} skip_buf rows; "
      f"residual add_rq banks; 6 blocks (sppf, 2x upsample, 2x attn, detect)")
