#!/usr/bin/env python3
# Copyright (c) 2026 vibeyolo
# SPDX-License-Identifier: Apache-2.0
#
# power.py — first-order power / energy rollup for the YOLO26n accelerator.
#
# COARSE by nature: dynamic power = activity × C × V² × f, and we do NOT have
# gate-level toggle rates, so the per-op energy constants in sram_model.PDKS are
# scaling estimates (Horowitz-class numbers, node-scaled). Treat the total as
# ±2-3×. What IS robust here is the *breakdown* — it shows the watts live in
# memory traffic (weights + activations), not the multipliers, which is the
# usual accelerator result and the right thing to optimize.
#
# Energy is counted as work actually performed per frame (network MACs and
# byte movements), times FPS, plus leakage = density × die area. Swap the PDK
# energy knobs (or a TSMC profile) and re-run; same flow as chip_area.py.
#
#   PDK=sky130 python3 tools/power.py
#   python3 tools/power.py --pdk n16 --scale-report <variant>.md

import os, sys, argparse
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sram_model as sm
import sram_bw, chip_area as ca

II = sram_bw.II_MAGIC                      # bottleneck stage cycles (throughput.py)


def main():
    ap = argparse.ArgumentParser(description="first-order power rollup")
    ap.add_argument("--pdk", default=os.environ.get("PDK", "n16"),
                    choices=list(sm.PDKS))
    ap.add_argument("--scale-report", default=sram_bw.BAL)
    ap.add_argument("--no-weight-fetch", action="store_true",
                    help="model weights as hardwired constants (no ROM read energy)")
    args = ap.parse_args()
    pdk = sm.set_pdk(args.pdk); sm._sync()
    rows = sram_bw.parse_balanced(args.scale_report)

    fps = pdk.clk_hz / II

    # ── work performed per frame ─────────────────────────────────────────
    # network multiplies (dense): cout·Hout·Wout·K²·cin
    macs_frame = sum(r["cout"]*r["h"]*r["w"]*r["k"]**2*r["cin"] for r in rows)
    # activation byte traffic: write each output pixel; linebuf re-reads K
    # columns × cin per output position (K row-buffers).
    act_wr_bits = sum(r["cout"]*r["h"]*r["w"] for r in rows) * 8
    act_rd_bits = sum(r["k"]*r["cin"]*r["h"]*r["w"] for r in rows) * 8
    # weight fetches: one int8 weight per MAC (upper bound; constants may fold).
    wt_bits = 0 if args.no_weight_fetch else macs_frame * 8

    # ── energy per frame (pJ) ────────────────────────────────────────────
    e_compute = macs_frame * pdk.e_mac_pj
    e_act     = (act_wr_bits + act_rd_bits) * pdk.e_mem_pj_bit
    e_wt      = wt_bits * pdk.e_mem_pj_bit
    e_dyn     = e_compute + e_act + e_wt
    e_clk     = pdk.clk_frac * e_dyn
    e_frame   = e_dyn + e_clk                       # pJ/frame (dynamic)

    p_dyn  = e_frame * 1e-12 * fps                  # W
    # leakage: density × die area (logic + rom + sram), reuse chip_area math.
    tot_units = sum(r["ppix"]*r["pcout"]*(r["k"]**2*r["pcin"]) for r in rows)
    a8 = ca.mac8_um2(pdk) or (ca.mac8_gates()*pdk.gate_um2)
    logic_mm2 = tot_units*a8*ca.OVERHEAD/ca.LOGIC_UTIL/1e6
    rom_mm2   = sum(r["k"]**2*r["cin"]*r["cout"]*8 for r in rows)*pdk.rom_um2_per_bit/1e6
    sram_mm2  = sum(t.area_um2 for t in (sram_bw.tile(m) for m in sram_bw.enumerate_mems(rows)))/1e6
    area_mm2  = logic_mm2 + rom_mm2 + sram_mm2
    p_leak = pdk.leak_mw_mm2 * area_mm2 / 1e3       # W

    p_tot = p_dyn + p_leak
    tops    = macs_frame * 2 * fps / 1e12           # 2 ops/MAC
    tops_w  = tops / p_tot
    j_frame = p_tot / fps

    def W(pj):  return pj*1e-12*fps
    L=[]; P=L.append
    P(f"# Power estimate — PDK `{pdk.name}` · {fps:,.0f} FPS @ {pdk.clk_hz/1e9:g} GHz\n")
    P("_Generated by `tools/power.py`. **Coarse (±2-3×)** — per-op energy is "
      "node-scaled, not gate-level. The breakdown (where watts go) is the "
      "trustworthy part._\n")
    P("| term | energy/frame | power | share |")
    P("|------|-------------:|------:|------:|")
    for name, pj in [("Compute (MACs)", e_compute),
                     ("Activation SRAM R/W", e_act),
                     ("Weight fetch" + (" (folded → 0)" if args.no_weight_fetch else ""), e_wt),
                     ("Clock tree", e_clk)]:
        P(f"| {name} | {pj/1e6:,.2f} µJ | {W(pj):.3f} W | {pj/e_frame*100:4.1f}% |")
    P(f"| **Dynamic total** | **{e_frame/1e6:,.2f} µJ** | **{p_dyn:.2f} W** | 100% |")
    P(f"| Leakage ({pdk.leak_mw_mm2:g} mW/mm² × {area_mm2:,.0f} mm²) | — | {p_leak:.2f} W | — |")
    P(f"| **TOTAL** | **{j_frame*1e3:,.2f} mJ/frame** | **{p_tot:.2f} W** | — |\n")
    P("| efficiency | value |")
    P("|-----------|------:|")
    P(f"| peak int8 throughput | {tops:.0f} TOPS |")
    P(f"| energy efficiency | **{tops_w:.1f} TOPS/W** |")
    P(f"| energy per inference | {j_frame*1e3:.2f} mJ |")
    P(f"| network MACs/frame | {macs_frame/1e9:.2f} GMAC |\n")
    P("> Weight fetch assumes one int8 ROM read per MAC (upper bound). A "
      "fixed-function chip can hardwire the constant weights — rerun with "
      "`--no-weight-fetch` to see that floor.")

    out = os.path.join(ca.ROOT, "reports", f"POWER_{pdk.name}.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out,"w").write("\n".join(L)+"\n")
    print(f"[pdk={pdk.name}] {p_tot:.2f} W  ({p_dyn:.2f} dyn + {p_leak:.2f} leak) "
          f"@ {fps:,.0f} FPS -> {tops_w:.1f} TOPS/W, {j_frame*1e3:.2f} mJ/frame")
    print(f"  compute {W(e_compute):.2f}W  act {W(e_act):.2f}W  "
          f"weights {W(e_wt):.2f}W  clk {W(e_clk):.2f}W")
    print(f"wrote {os.path.relpath(out, ca.ROOT)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
