#!/usr/bin/env python3
# Copyright (c) 2026 vibeyolo
# SPDX-License-Identifier: Apache-2.0
#
# Static throughput / latency sign-off for the YOLO26n accelerator.
#
# The chip is a frame-level streaming dataflow: each layer/block is dedicated
# hardware, and (with per-stage frame double-buffering) stages process
# successive frames concurrently. Therefore:
#
#   * Throughput  = frame initiation interval (II) = the SLOWEST single stage.
#                   Spec: II <= T_FRAME = 100,000 cyc  ->  >= 10,000 FPS @ 1 GHz.
#   * Latency     = time for one frame to traverse the pipeline = sum of stage
#                   times along the dependency critical path (pipeline fill).
#
# Conv-stage cycles come from the authoritative balanced (production) scale
# report. Block cycles are the validated DV numbers where measured, and clearly
# marked analytic estimates for the small frame-store ops (SPPF / upsamples)
# which sit far below the bottleneck and so do not affect the II conclusion.

import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BAL  = os.path.join(ROOT, "integ/generated/scale/scale_report_balanced.md")
T_FRAME = 100_000
CLK_HZ  = 1e9

def parse_balanced(path):
    convs = []
    with open(path) as f:
        for line in f:
            m = re.match(r"\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|.*\|\s*(\d+)\s*\|\s*(yes|no)\s*\|\s*$", line)
            if m:
                convs.append((int(m.group(1)), m.group(2).strip(),
                              int(m.group(3)), m.group(4)))
    return convs

# Block stages. (name, cycles, source). source: 'dv'=measured in block DV,
# 'analytic'=H_out*W_out frame-store estimate (channel-parallel, 1 px/cyc + fill).
BLOCKS = [
    ("SPPF /model.9 (maxpool x3 + concat, 20^2 C128)",        400*3 + 400 + 64, "analytic"),
    ("upsample /model.11+12 (P4->P3, store 20^2 + concat 40^2)", 40*40 + 20*20 + 64, "analytic"),
    ("upsample /model.14+15 (P3->det, store 40^2 + concat 80^2)", 80*80 + 40*40 + 64, "analytic"),
    ("attn PSA /model.10 (flash_attn HEADS2 N400)",            74_911, "dv"),
    ("attn A2C2f /model.22 (flash_attn HEADS2 N400)",          74_911, "dv"),
    # 8,400 decode + 43,583 worst-case topk (2-level sift-down) + ~319 gather.
    # (Was 84,700 with the old 1-level sift, topk worst = 75,981.)
    ("detect head /model.23 (decode + topk300 + gather)",      52_302, "dv"),
]

def main():
    if not os.path.exists(BAL):
        sys.exit(f"missing balanced report: {BAL}")
    convs = parse_balanced(BAL)
    assert len(convs) == 102, f"expected 102 conv layers, got {len(convs)}"

    conv_cycles = [c for _, _, c, _ in convs]
    misses = [(i, n, c) for i, n, c, m in convs if m != "yes" or c > T_FRAME]

    stages = [("conv L%d %s" % (i, n), c, "scale") for i, n, c, _ in convs] \
           + [(n, c, s) for n, c, s in BLOCKS]

    all_cycles = conv_cycles + [c for _, c, _ in BLOCKS]
    II = max(all_cycles)
    bottleneck = max(stages, key=lambda s: s[1])
    latency = sum(all_cycles)          # critical-path upper bound (all sequential)
    fps_tp  = CLK_HZ / II
    fps_seq = CLK_HZ / latency         # if NO double-buffering (1 frame in flight)

    lines = []
    P = lines.append
    P("# YOLO26n — throughput / latency sign-off\n")
    P(f"_Generated by `tools/throughput.py` from `{os.path.relpath(BAL, ROOT)}` "
      f"(balanced production config) + validated block DV numbers._\n")
    P(f"**Spec:** `T_FRAME = {T_FRAME:,}` cyc/frame  →  ≥ {CLK_HZ/T_FRAME:,.0f} FPS @ 1 GHz "
      f"(frame-level pipelined dataflow, per-stage double-buffered).\n")

    P("## Result\n")
    P("| metric | value | spec | verdict |")
    P("|--------|-------|------|---------|")
    P(f"| Throughput (II = slowest stage) | **{II:,} cyc** | ≤ {T_FRAME:,} | "
      f"{'✅ PASS' if II <= T_FRAME else '❌ FAIL'} |")
    P(f"| → frames/sec @ 1 GHz | **{fps_tp:,.0f} FPS** | ≥ {CLK_HZ/T_FRAME:,.0f} | "
      f"{'✅ PASS' if fps_tp >= CLK_HZ/T_FRAME else '❌ FAIL'} |")
    P(f"| Bottleneck stage | `{bottleneck[0]}` | — | — |")
    P(f"| Latency (critical-path fill, all stages) | {latency:,} cyc ≈ {latency/CLK_HZ*1e3:.2f} ms | (none) | informational |")
    P(f"| Throughput if NOT double-buffered (1 frame in flight) | {fps_seq:,.0f} FPS | — | (design uses double-buffering) |")
    P(f"| Conv stages | {len(convs)} | — | — |")
    P(f"| Conv stages over T_FRAME | {len([c for c in conv_cycles if c>T_FRAME])} | 0 | "
      f"{'✅' if not any(c>T_FRAME for c in conv_cycles) else '❌'} |\n")

    P("## Stage cycle distribution (conv)\n")
    import collections
    hist = collections.Counter(conv_cycles)
    P("| cycles/frame | # conv stages |")
    P("|-------------:|--------------:|")
    for cyc in sorted(hist):
        P(f"| {cyc:,} | {hist[cyc]} |")
    P("")

    P("## Top 10 slowest stages\n")
    P("| stage | cyc/frame | source |")
    P("|-------|----------:|--------|")
    for name, cyc, src in sorted(stages, key=lambda s: -s[1])[:10]:
        P(f"| {name} | {cyc:,} | {src} |")
    P("")

    P("## Block stages\n")
    P("| block | cyc/frame | source |")
    P("|-------|----------:|--------|")
    for name, cyc, src in BLOCKS:
        flag = "" if cyc <= T_FRAME else " ⚠️"
        P(f"| {name} | {cyc:,}{flag} | {src} |")
    P("")
    P("> `dv` = measured in the block's Verilator DV; `analytic` = "
      "H_out·W_out frame-store estimate (channel-parallel ≈1 px/cyc + fill). "
      "The analytic blocks sit far below the bottleneck, so their precision "
      "does not affect the throughput verdict.\n")

    if misses:
        P("## ⚠️ Stages missing T_FRAME\n")
        for i, n, c in misses:
            P(f"- L{i} `{n}`: {c:,} cyc")
    else:
        P("**All 102 conv stages and all blocks meet T_FRAME.**")

    out = os.path.join(ROOT, "TIMING.md")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")

    # console summary
    print(f"II (throughput)   = {II:,} cyc  -> {fps_tp:,.0f} FPS @ 1 GHz   "
          f"[{'PASS' if II<=T_FRAME else 'FAIL'} vs {T_FRAME:,}]")
    print(f"bottleneck stage  = {bottleneck[0]}")
    print(f"latency (fill)    = {latency:,} cyc ≈ {latency/CLK_HZ*1e3:.2f} ms")
    print(f"conv over T_FRAME = {len([c for c in conv_cycles if c>T_FRAME])}")
    print(f"wrote {os.path.relpath(out, ROOT)}")
    return 0 if II <= T_FRAME and not misses else 1

if __name__ == "__main__":
    sys.exit(main())
